// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InternalTokenResponseTokenType.
const (
	InternalTokenResponseTokenTypeBearer InternalTokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the InternalTokenResponseTokenType enum.
func (e InternalTokenResponseTokenType) Valid() bool {
	switch e {
	case InternalTokenResponseTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for JwkAlg.
const (
	EdDSA JwkAlg = "EdDSA"
)

// Valid indicates whether the value is a known member of the JwkAlg enum.
func (e JwkAlg) Valid() bool {
	switch e {
	case EdDSA:
		return true
	default:
		return false
	}
}

// Defines values for JwkCrv.
const (
	Ed25519 JwkCrv = "Ed25519"
)

// Valid indicates whether the value is a known member of the JwkCrv enum.
func (e JwkCrv) Valid() bool {
	switch e {
	case Ed25519:
		return true
	default:
		return false
	}
}

// Defines values for JwkKty.
const (
	OKP JwkKty = "OKP"
)

// Valid indicates whether the value is a known member of the JwkKty enum.
func (e JwkKty) Valid() bool {
	switch e {
	case OKP:
		return true
	default:
		return false
	}
}

// Defines values for JwkUse.
const (
	Sig JwkUse = "sig"
)

// Valid indicates whether the value is a known member of the JwkUse enum.
func (e JwkUse) Valid() bool {
	switch e {
	case Sig:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin       Role = "admin"
	Analyst     Role = "analyst"
	Approver    Role = "approver"
	DataManager Role = "data_manager"
	Officer     Role = "officer"
	Viewer      Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Analyst:
		return true
	case Approver:
		return true
	case DataManager:
		return true
	case Officer:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for ServiceTokenRequestAudience.
const (
	ServiceTokenRequestAudienceForecast     ServiceTokenRequestAudience = "forecast"
	ServiceTokenRequestAudienceGenai        ServiceTokenRequestAudience = "genai"
	ServiceTokenRequestAudienceIdentity     ServiceTokenRequestAudience = "identity"
	ServiceTokenRequestAudienceNotification ServiceTokenRequestAudience = "notification"
	ServiceTokenRequestAudienceOptimize     ServiceTokenRequestAudience = "optimize"
	ServiceTokenRequestAudienceSurveillance ServiceTokenRequestAudience = "surveillance"
	ServiceTokenRequestAudienceWorkflow     ServiceTokenRequestAudience = "workflow"
)

// Valid indicates whether the value is a known member of the ServiceTokenRequestAudience enum.
func (e ServiceTokenRequestAudience) Valid() bool {
	switch e {
	case ServiceTokenRequestAudienceForecast:
		return true
	case ServiceTokenRequestAudienceGenai:
		return true
	case ServiceTokenRequestAudienceIdentity:
		return true
	case ServiceTokenRequestAudienceNotification:
		return true
	case ServiceTokenRequestAudienceOptimize:
		return true
	case ServiceTokenRequestAudienceSurveillance:
		return true
	case ServiceTokenRequestAudienceWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for ServiceTokenRequestService.
const (
	ServiceTokenRequestServiceForecast     ServiceTokenRequestService = "forecast"
	ServiceTokenRequestServiceGateway      ServiceTokenRequestService = "gateway"
	ServiceTokenRequestServiceGenai        ServiceTokenRequestService = "genai"
	ServiceTokenRequestServiceIngestWorker ServiceTokenRequestService = "ingest-worker"
	ServiceTokenRequestServiceNotification ServiceTokenRequestService = "notification"
	ServiceTokenRequestServiceOptimize     ServiceTokenRequestService = "optimize"
	ServiceTokenRequestServiceSurveillance ServiceTokenRequestService = "surveillance"
	ServiceTokenRequestServiceWorkflow     ServiceTokenRequestService = "workflow"
)

// Valid indicates whether the value is a known member of the ServiceTokenRequestService enum.
func (e ServiceTokenRequestService) Valid() bool {
	switch e {
	case ServiceTokenRequestServiceForecast:
		return true
	case ServiceTokenRequestServiceGateway:
		return true
	case ServiceTokenRequestServiceGenai:
		return true
	case ServiceTokenRequestServiceIngestWorker:
		return true
	case ServiceTokenRequestServiceNotification:
		return true
	case ServiceTokenRequestServiceOptimize:
		return true
	case ServiceTokenRequestServiceSurveillance:
		return true
	case ServiceTokenRequestServiceWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for ServiceTokenResponseTokenType.
const (
	ServiceTokenResponseTokenTypeBearer ServiceTokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the ServiceTokenResponseTokenType enum.
func (e ServiceTokenResponseTokenType) Valid() bool {
	switch e {
	case ServiceTokenResponseTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for Healthz200JSONResponseBodyStatus.
const (
	Ok Healthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the Healthz200JSONResponseBodyStatus enum.
func (e Healthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Readyz200JSONResponseBodyStatus.
const (
	Ready Readyz200JSONResponseBodyStatus = "ready"
)

// Valid indicates whether the value is a known member of the Readyz200JSONResponseBodyStatus enum.
func (e Readyz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// InternalTokenResponse defines model for InternalTokenResponse.
type InternalTokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Giây hiệu lực của access token.
	//
	// Examples: 900
	ExpiresIn int `json:"expires_in"`

	// RefreshExpiresIn Examples: 604800
	RefreshExpiresIn int `json:"refresh_expires_in"`

	// RefreshToken Chuỗi ngẫu nhiên 256-bit; identity chỉ lưu HASH.
	RefreshToken string                         `json:"refresh_token"`
	TokenType    InternalTokenResponseTokenType `json:"token_type"`
	User         User                           `json:"user"`
}

// InternalTokenResponseTokenType defines model for InternalTokenResponse.TokenType.
type InternalTokenResponseTokenType string

// Jwk defines model for Jwk.
type Jwk struct {
	Alg JwkAlg `json:"alg"`
	Crv JwkCrv `json:"crv"`
	Kid string `json:"kid"`
	Kty JwkKty `json:"kty"`
	Use JwkUse `json:"use"`

	// X Khoá công khai, base64url.
	X string `json:"x"`
}

// JwkAlg defines model for Jwk.Alg.
type JwkAlg string

// JwkCrv defines model for Jwk.Crv.
type JwkCrv string

// JwkKty defines model for Jwk.Kty.
type JwkKty string

// JwkUse defines model for Jwk.Use.
type JwkUse string

// Jwks defines model for Jwks.
type Jwks struct {
	Keys []Jwk `json:"keys"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password *string `json:"password,omitempty"`
	Username string  `json:"username"`
}

// Problem RFC 9457 problem details (docs/09 §6.3).
type Problem struct {
	// Code Mã lỗi ổn định dạng `<service>.<snake_case>` — danh mục ở contracts/errors.md.
	//
	// Examples: common.validation_error
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId string  `json:"request_id"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// Role defines model for Role.
type Role string

// ServiceTokenRequest defines model for ServiceTokenRequest.
type ServiceTokenRequest struct {
	Audience     ServiceTokenRequestAudience `json:"audience"`
	ClientSecret *string                     `json:"client_secret,omitempty"`
	Service      ServiceTokenRequestService  `json:"service"`
}

// ServiceTokenRequestAudience defines model for ServiceTokenRequest.Audience.
type ServiceTokenRequestAudience string

// ServiceTokenRequestService defines model for ServiceTokenRequest.Service.
type ServiceTokenRequestService string

// ServiceTokenResponse defines model for ServiceTokenResponse.
type ServiceTokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Examples: 300
	ExpiresIn int                           `json:"expires_in"`
	TokenType ServiceTokenResponseTokenType `json:"token_type"`
}

// ServiceTokenResponseTokenType defines model for ServiceTokenResponse.TokenType.
type ServiceTokenResponseTokenType string

// User defines model for User.
type User struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`

	// OrgId Đơn vị trực thuộc (CDC tỉnh / bệnh viện) — quyết định phạm vi dữ liệu được xử lý.
	OrgId    string `json:"org_id"`
	Roles    []Role `json:"roles"`
	Username string `json:"username"`
}

// NotFound RFC 9457 problem details (docs/09 §6.3).
type NotFound = Problem

// Unauthenticated RFC 9457 problem details (docs/09 §6.3).
type Unauthenticated = Problem

// Unavailable RFC 9457 problem details (docs/09 §6.3).
type Unavailable = Problem

// ValidationError RFC 9457 problem details (docs/09 §6.3).
type ValidationError = Problem

// Healthz200JSONResponseBodyStatus defines parameters for Healthz.
type Healthz200JSONResponseBodyStatus string

// Readyz200JSONResponseBodyStatus defines parameters for Readyz.
type Readyz200JSONResponseBodyStatus string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// IssueServiceTokenJSONRequestBody defines body for IssueServiceToken for application/json ContentType.
type IssueServiceTokenJSONRequestBody = ServiceTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthz Tiến trình còn sống (không kiểm phụ thuộc)
	// (GET /healthz)
	Healthz(c *gin.Context)
	// GetJwks Khoá công khai (JWKS, Ed25519) để xác minh access token người dùng
	// (GET /internal/v1/.well-known/jwks.json)
	GetJwks(c *gin.Context)
	// Login Đăng nhập (gateway gọi). Trả cả refresh token để GATEWAY đặt cookie HttpOnly.
	// (POST /internal/v1/auth/login)
	Login(c *gin.Context)
	// Logout Thu hồi refresh token (đăng xuất)
	// (POST /internal/v1/auth/logout)
	Logout(c *gin.Context)
	// RefreshToken Đổi refresh token lấy cặp token mới (XOAY VÒNG)
	// (POST /internal/v1/auth/refresh)
	RefreshToken(c *gin.Context)
	// IssueServiceToken Cấp token DỊCH VỤ (5 phút) cho một service gọi service khác
	// (POST /internal/v1/service-tokens)
	IssueServiceToken(c *gin.Context)
	// GetUser Thông tin người dùng (gateway dùng cho `GET /me`)
	// (GET /internal/v1/users/{user_id})
	GetUser(c *gin.Context, userId openapi_types.UUID)
	// Readyz Sẵn sàng nhận tải (đã kiểm phụ thuộc)
	// (GET /readyz)
	Readyz(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// GetJwks operation middleware
func (siw *ServerInterfaceWrapper) GetJwks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJwks(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// IssueServiceToken operation middleware
func (siw *ServerInterfaceWrapper) IssueServiceToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IssueServiceToken(c)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUser(c, userId)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Readyz(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/internal/v1/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/internal/v1/auth/refresh", wrapper.RefreshToken)
	router.POST(options.BaseURL+"/internal/v1/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/internal/v1/users/:user_id", wrapper.GetUser)
	router.GET(options.BaseURL+"/internal/v1/.well-known/jwks.json", wrapper.GetJwks)
	router.POST(options.BaseURL+"/internal/v1/service-tokens", wrapper.IssueServiceToken)
	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/readyz", wrapper.Readyz)
}

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthenticatedApplicationProblemPlusJSONResponse Problem

type UnavailableApplicationProblemPlusJSONResponse Problem

type ValidationErrorApplicationProblemPlusJSONResponse Problem

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse struct {
	Status Healthz200JSONResponseBodyStatus `json:"status"`
}

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Healthz500ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response Healthz500ApplicationProblemPlusJSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetJwksRequestObject struct {
}

type GetJwksResponseObject interface {
	VisitGetJwksResponse(w http.ResponseWriter) error
}

type GetJwks200JSONResponse Jwks

func (response GetJwks200JSONResponse) VisitGetJwksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJwks503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetJwks503ApplicationProblemPlusJSONResponse) VisitGetJwksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse InternalTokenResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response Login503ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response Logout400ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Logout503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response Logout503ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse InternalTokenResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response RefreshToken400ApplicationProblemPlusJSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response RefreshToken401ApplicationProblemPlusJSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response RefreshToken503ApplicationProblemPlusJSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type IssueServiceTokenRequestObject struct {
	Body *IssueServiceTokenJSONRequestBody
}

type IssueServiceTokenResponseObject interface {
	VisitIssueServiceTokenResponse(w http.ResponseWriter) error
}

type IssueServiceToken200JSONResponse ServiceTokenResponse

func (response IssueServiceToken200JSONResponse) VisitIssueServiceTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type IssueServiceToken400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response IssueServiceToken400ApplicationProblemPlusJSONResponse) VisitIssueServiceTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type IssueServiceToken401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response IssueServiceToken401ApplicationProblemPlusJSONResponse) VisitIssueServiceTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type IssueServiceToken503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response IssueServiceToken503ApplicationProblemPlusJSONResponse) VisitIssueServiceTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserRequestObject struct {
	UserId openapi_types.UUID `json:"user_id"`
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse User

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUser401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetUser401ApplicationProblemPlusJSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetUser404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetUser404ApplicationProblemPlusJSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUser503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetUser503ApplicationProblemPlusJSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200JSONResponse struct {
	Status Readyz200JSONResponseBodyStatus `json:"status"`
}

func (response Readyz200JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Readyz503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response Readyz503ApplicationProblemPlusJSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Healthz Tiến trình còn sống (không kiểm phụ thuộc)
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// GetJwks Khoá công khai (JWKS, Ed25519) để xác minh access token người dùng
	// (GET /internal/v1/.well-known/jwks.json)
	GetJwks(ctx context.Context, request GetJwksRequestObject) (GetJwksResponseObject, error)
	// Login Đăng nhập (gateway gọi). Trả cả refresh token để GATEWAY đặt cookie HttpOnly.
	// (POST /internal/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Thu hồi refresh token (đăng xuất)
	// (POST /internal/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RefreshToken Đổi refresh token lấy cặp token mới (XOAY VÒNG)
	// (POST /internal/v1/auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// IssueServiceToken Cấp token DỊCH VỤ (5 phút) cho một service gọi service khác
	// (POST /internal/v1/service-tokens)
	IssueServiceToken(ctx context.Context, request IssueServiceTokenRequestObject) (IssueServiceTokenResponseObject, error)
	// GetUser Thông tin người dùng (gateway dùng cho `GET /me`)
	// (GET /internal/v1/users/{user_id})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
	// Readyz Sẵn sàng nhận tải (đã kiểm phụ thuộc)
	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(ctx *gin.Context) {
	var request HealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJwks operation middleware
func (sh *strictHandler) GetJwks(ctx *gin.Context) {
	var request GetJwksRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetJwks(ctx, request.(GetJwksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJwks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetJwksResponseObject); ok {
		if err := validResponse.VisitGetJwksResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *gin.Context) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IssueServiceToken operation middleware
func (sh *strictHandler) IssueServiceToken(ctx *gin.Context) {
	var request IssueServiceTokenRequestObject

	var body IssueServiceTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.IssueServiceToken(ctx, request.(IssueServiceTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IssueServiceToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(IssueServiceTokenResponseObject); ok {
		if err := validResponse.VisitIssueServiceTokenResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(ctx *gin.Context, userId openapi_types.UUID) {
	var request GetUserRequestObject

	request.UserId = userId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx, request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		if err := validResponse.VisitGetUserResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(ctx *gin.Context) {
	var request ReadyzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx, request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		if err := validResponse.VisitReadyzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
