// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DataSource.
const (
	Estimated DataSource = "estimated"
	Imputed   DataSource = "imputed"
	Real      DataSource = "real"
	Simulated DataSource = "simulated"
)

// Valid indicates whether the value is a known member of the DataSource enum.
func (e DataSource) Valid() bool {
	switch e {
	case Estimated:
		return true
	case Imputed:
		return true
	case Real:
		return true
	case Simulated:
		return true
	default:
		return false
	}
}

// Defines values for ExplanationFactorFamily.
const (
	Climate      ExplanationFactorFamily = "climate"
	Other        ExplanationFactorFamily = "other"
	RecentCases  ExplanationFactorFamily = "recent_cases"
	SeasonalNorm ExplanationFactorFamily = "seasonal_norm"
)

// Valid indicates whether the value is a known member of the ExplanationFactorFamily enum.
func (e ExplanationFactorFamily) Valid() bool {
	switch e {
	case Climate:
		return true
	case Other:
		return true
	case RecentCases:
		return true
	case SeasonalNorm:
		return true
	default:
		return false
	}
}

// Defines values for ForecastFlag.
const (
	EstimatedInputs             ForecastFlag = "estimated_inputs"
	OutOfValidatedPeriod        ForecastFlag = "out_of_validated_period"
	OutbreakUnderpredictionRisk ForecastFlag = "outbreak_underprediction_risk"
	StaleData                   ForecastFlag = "stale_data"
)

// Valid indicates whether the value is a known member of the ForecastFlag enum.
func (e ForecastFlag) Valid() bool {
	switch e {
	case EstimatedInputs:
		return true
	case OutOfValidatedPeriod:
		return true
	case OutbreakUnderpredictionRisk:
		return true
	case StaleData:
		return true
	default:
		return false
	}
}

// Defines values for GeoJsonFeatureCollectionFeaturesType.
const (
	Feature GeoJsonFeatureCollectionFeaturesType = "Feature"
)

// Valid indicates whether the value is a known member of the GeoJsonFeatureCollectionFeaturesType enum.
func (e GeoJsonFeatureCollectionFeaturesType) Valid() bool {
	switch e {
	case Feature:
		return true
	default:
		return false
	}
}

// Defines values for GeoJsonFeatureCollectionType.
const (
	FeatureCollection GeoJsonFeatureCollectionType = "FeatureCollection"
)

// Valid indicates whether the value is a known member of the GeoJsonFeatureCollectionType enum.
func (e GeoJsonFeatureCollectionType) Valid() bool {
	switch e {
	case FeatureCollection:
		return true
	default:
		return false
	}
}

// Defines values for Horizon.
const (
	N1 Horizon = 1
	N2 Horizon = 2
	N3 Horizon = 3
	N6 Horizon = 6
)

// Valid indicates whether the value is a known member of the Horizon enum.
func (e Horizon) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	case N6:
		return true
	default:
		return false
	}
}

// Defines values for JobKind.
const (
	JobKindForecastRun JobKind = "forecast_run"
)

// Valid indicates whether the value is a known member of the JobKind enum.
func (e JobKind) Valid() bool {
	switch e {
	case JobKindForecastRun:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusCancelled JobStatus = "cancelled"
	JobStatusFailed    JobStatus = "failed"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCancelled:
		return true
	case JobStatusFailed:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for LimitationSeverity.
const (
	LimitationSeverityHigh     LimitationSeverity = "high"
	LimitationSeverityInfo     LimitationSeverity = "info"
	LimitationSeverityModerate LimitationSeverity = "moderate"
)

// Valid indicates whether the value is a known member of the LimitationSeverity enum.
func (e LimitationSeverity) Valid() bool {
	switch e {
	case LimitationSeverityHigh:
		return true
	case LimitationSeverityInfo:
		return true
	case LimitationSeverityModerate:
		return true
	default:
		return false
	}
}

// Defines values for ModelVersionStatus.
const (
	Approved  ModelVersionStatus = "approved"
	Candidate ModelVersionStatus = "candidate"
	Retired   ModelVersionStatus = "retired"
)

// Valid indicates whether the value is a known member of the ModelVersionStatus enum.
func (e ModelVersionStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Candidate:
		return true
	case Retired:
		return true
	default:
		return false
	}
}

// Defines values for Region.
const (
	Bắc   Region = "Bắc"
	Nam   Region = "Nam"
	Trung Region = "Trung"
)

// Valid indicates whether the value is a known member of the Region enum.
func (e Region) Valid() bool {
	switch e {
	case Bắc:
		return true
	case Nam:
		return true
	case Trung:
		return true
	default:
		return false
	}
}

// Defines values for ReliabilityRegionLevel.
const (
	ReliabilityRegionLevelEqualToSeasonalBaseline ReliabilityRegionLevel = "equal_to_seasonal_baseline"
	ReliabilityRegionLevelHigh                    ReliabilityRegionLevel = "high"
	ReliabilityRegionLevelHighNormalYears         ReliabilityRegionLevel = "high_normal_years"
	ReliabilityRegionLevelLowInOutbreakYears      ReliabilityRegionLevel = "low_in_outbreak_years"
)

// Valid indicates whether the value is a known member of the ReliabilityRegionLevel enum.
func (e ReliabilityRegionLevel) Valid() bool {
	switch e {
	case ReliabilityRegionLevelEqualToSeasonalBaseline:
		return true
	case ReliabilityRegionLevelHigh:
		return true
	case ReliabilityRegionLevelHighNormalYears:
		return true
	case ReliabilityRegionLevelLowInOutbreakYears:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin       Role = "admin"
	Analyst     Role = "analyst"
	Approver    Role = "approver"
	DataManager Role = "data_manager"
	Officer     Role = "officer"
	Viewer      Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Analyst:
		return true
	case Approver:
		return true
	case DataManager:
		return true
	case Officer:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for RunMode.
const (
	Backtest         RunMode = "backtest"
	LiveExperimental RunMode = "live_experimental"
)

// Valid indicates whether the value is a known member of the RunMode enum.
func (e RunMode) Valid() bool {
	switch e {
	case Backtest:
		return true
	case LiveExperimental:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusCancelled   RunStatus = "cancelled"
	RunStatusCompleted   RunStatus = "completed"
	RunStatusFailed      RunStatus = "failed"
	RunStatusInterrupted RunStatus = "interrupted"
	RunStatusQueued      RunStatus = "queued"
	RunStatusRunning     RunStatus = "running"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusCancelled:
		return true
	case RunStatusCompleted:
		return true
	case RunStatusFailed:
		return true
	case RunStatusInterrupted:
		return true
	case RunStatusQueued:
		return true
	case RunStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenResponseTokenType enum.
func (e TokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// CreateForecastRunRequest defines model for CreateForecastRunRequest.
type CreateForecastRunRequest struct {
	// DataVersion Mặc định là bản mới nhất.
	DataVersion *string `json:"data_version,omitempty"`
	Mode        RunMode `json:"mode"`

	// ModelVersion Mặc định là phiên bản `approved` hiện hành.
	ModelVersion *string `json:"model_version,omitempty"`

	// OriginMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	OriginMonth YearMonth `json:"origin_month"`
}

// DataSource `real` đo thật; `estimated` ước lượng small-area (2011–2025); `imputed` điền khuyết; `simulated` giả lập.
// UI PHẢI phân biệt rõ, không để dữ liệu không-thật trông như thật (docs/10 luật T2).
type DataSource string

// DataVersion defines model for DataVersion.
type DataVersion struct {
	// FirstMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	FirstMonth *YearMonth `json:"first_month,omitempty"`

	// LastMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	LastMonth   *YearMonth `json:"last_month,omitempty"`
	PublishedAt time.Time  `json:"published_at"`

	// RealShare Tỉ lệ dòng dữ liệu `real` trong phiên bản.
	RealShare float64 `json:"real_share"`

	// Version Examples: v0.2.0
	Version string `json:"version"`
}

// Explanation defines model for Explanation.
type Explanation struct {
	// BaseValue Giá trị nền (kỳ vọng) của mô hình.
	BaseValue float64 `json:"base_value"`

	// Factors Top-k yếu tố theo |contribution| giảm dần.
	Factors []ExplanationFactor `json:"factors"`

	// Horizon Tầm dự báo — số tháng tính từ tháng neo (`origin_month`).
	Horizon Horizon `json:"horizon"`

	// Meta Provenance — bắt buộc trong mọi response chứa số liệu mô hình (docs/09 §6.5, docs/10 luật T3).
	Meta       Meta   `json:"meta"`
	ProvinceId string `json:"province_id"`
}

// ExplanationFactor defines model for ExplanationFactor.
type ExplanationFactor struct {
	// Contribution Đóng góp SHAP vào dự báo (đơn vị của đầu ra mô hình).
	Contribution float64                 `json:"contribution"`
	Family       ExplanationFactorFamily `json:"family"`

	// Feature Examples: cases_lag_1
	Feature string `json:"feature"`

	// Value Giá trị đặc trưng đầu vào.
	Value *float64 `json:"value"`
}

// ExplanationFactorFamily defines model for ExplanationFactor.Family.
type ExplanationFactorFamily string

// ForecastFlag `outbreak_underprediction_risk`: mô hình thiên thấp khi bùng dịch — cần chuyên môn xem xét.
// `estimated_inputs`: đầu vào có dữ liệu ước lượng. `stale_data`: dữ liệu quá hạn.
// `out_of_validated_period`: tháng neo sau giai đoạn đã kiểm chứng (2010).
type ForecastFlag string

// ForecastItem defines model for ForecastItem.
type ForecastItem struct {
	// BaseRate Tỉ lệ nền tháng vượt ngưỡng trong giai đoạn tham chiếu của phiên bản mô hình.
	BaseRate float64 `json:"base_rate"`

	// CasesPred Số ca dự báo trong tháng đích.
	CasesPred float64 `json:"cases_pred"`

	// CasesPredInterval Khoảng dự báo. **Hiện luôn `null`** — chưa có khoảng đã kiểm chứng độ phủ (docs/09 §10.2, Q4).
	// UI không được tự vẽ khoảng khi null.
	CasesPredInterval *PredictionInterval `json:"cases_pred_interval"`

	// ExceedProb Xác suất số ca tháng đích vượt ngưỡng P75. LUÔN hiển thị cùng `base_rate`.
	ExceedProb float64        `json:"exceed_prob"`
	Flags      []ForecastFlag `json:"flags"`

	// Horizon Tầm dự báo — số tháng tính từ tháng neo (`origin_month`).
	Horizon Horizon `json:"horizon"`

	// InputDataSources Tỉ trọng nguồn dữ liệu đầu vào của dự báo (cộng lại ≈ 1).
	InputDataSources InputDataSources `json:"input_data_sources"`
	ProvinceId       string           `json:"province_id"`
	Region           Region           `json:"region"`

	// Reliability Độ tin cậy theo vùng (docs/07 §12.4). Bảng tĩnh gắn với phiên bản mô hình.
	Reliability Reliability `json:"reliability"`

	// TargetMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	TargetMonth YearMonth `json:"target_month"`

	// ThresholdP75 Ngưỡng P75 cùng tháng dương lịch, cùng tỉnh, tính nhân quả.
	ThresholdP75 float64 `json:"threshold_p75"`
}

// ForecastRun defines model for ForecastRun.
type ForecastRun struct {
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	CreatedAt    time.Time  `json:"created_at"`
	DataVersion  string     `json:"data_version"`
	ErrorCode    *string    `json:"error_code,omitempty"`
	ModelVersion string     `json:"model_version"`

	// OriginMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	OriginMonth YearMonth          `json:"origin_month"`
	RunId       openapi_types.UUID `json:"run_id"`
	RunMode     RunMode            `json:"run_mode"`
	Status      RunStatus          `json:"status"`
}

// GeoJsonFeatureCollection defines model for GeoJsonFeatureCollection.
type GeoJsonFeatureCollection struct {
	Features []struct {
		Geometry   map[string]interface{}                       `json:"geometry"`
		Properties GeoJsonFeatureCollection_Features_Properties `json:"properties"`
		Type       GeoJsonFeatureCollectionFeaturesType         `json:"type"`
	} `json:"features"`
	Type GeoJsonFeatureCollectionType `json:"type"`
}

// GeoJsonFeatureCollection_Features_Properties defines model for GeoJsonFeatureCollection.Features.Properties.
type GeoJsonFeatureCollection_Features_Properties struct {
	ProvinceId           string                 `json:"province_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GeoJsonFeatureCollectionFeaturesType defines model for GeoJsonFeatureCollection.Features.Type.
type GeoJsonFeatureCollectionFeaturesType string

// GeoJsonFeatureCollectionType defines model for GeoJsonFeatureCollection.Type.
type GeoJsonFeatureCollectionType string

// Horizon Tầm dự báo — số tháng tính từ tháng neo (`origin_month`).
type Horizon int

// InputDataSources Tỉ trọng nguồn dữ liệu đầu vào của dự báo (cộng lại ≈ 1).
type InputDataSources struct {
	Estimated float64 `json:"estimated"`
	Imputed   float64 `json:"imputed"`
	Real      float64 `json:"real"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt  time.Time          `json:"created_at"`
	ErrorCode  *string            `json:"error_code,omitempty"`
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	JobId      openapi_types.UUID `json:"job_id"`

	// Kind Examples: forecast_run
	Kind     JobKind  `json:"kind"`
	Progress *float64 `json:"progress,omitempty"`

	// ResultRef URL tài nguyên kết quả khi thành công (vd `/api/v1/forecast-runs/{id}`).
	ResultRef *string   `json:"result_ref,omitempty"`
	Status    JobStatus `json:"status"`
}

// JobKind Examples: forecast_run
type JobKind string

// JobStatus defines model for Job.Status.
type JobStatus string

// LegendClass defines model for LegendClass.
type LegendClass struct {
	Label string  `json:"label"`
	Max   float64 `json:"max"`
	Min   float64 `json:"min"`
}

// Limitation defines model for Limitation.
type Limitation struct {
	// Evidence Tham chiếu experiment/mục model card chứa số đo.
	//
	// Examples: exp_016 §Bắc
	Evidence string `json:"evidence"`

	// Id Examples: L1
	Id       string             `json:"id"`
	Severity LimitationSeverity `json:"severity"`
	Summary  string             `json:"summary"`
	Title    string             `json:"title"`
}

// LimitationSeverity defines model for Limitation.Severity.
type LimitationSeverity string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password *string `json:"password,omitempty"`
	Username string  `json:"username"`
}

// Meta Provenance — bắt buộc trong mọi response chứa số liệu mô hình (docs/09 §6.5, docs/10 luật T3).
type Meta struct {
	// AsOf Thời điểm dữ liệu đầu vào được chốt.
	AsOf *time.Time `json:"as_of,omitempty"`

	// DataVersion Examples: v0.2.0
	DataVersion string    `json:"data_version"`
	GeneratedAt time.Time `json:"generated_at"`

	// LimitationsRef Examples: /api/v1/model-card/limitations
	LimitationsRef string `json:"limitations_ref"`

	// ModelVersion Examples: m4-r2@1.0.0
	ModelVersion string `json:"model_version"`

	// OriginMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	OriginMonth YearMonth          `json:"origin_month"`
	RunId       openapi_types.UUID `json:"run_id"`
	RunMode     RunMode            `json:"run_mode"`
}

// ModelCard defines model for ModelCard.
type ModelCard struct {
	IntendedUse  string   `json:"intended_use"`
	ModelVersion string   `json:"model_version"`
	NotFor       []string `json:"not_for"`
	Performance  struct {
		Alerting struct {
			BaseRateRange []float64 `json:"base_rate_range"`
			RocAucMean    float64   `json:"roc_auc_mean"`
			RocAucSd      float64   `json:"roc_auc_sd"`
		} `json:"alerting"`

		// MultiSeason Đánh giá nhiều mùa (exp_016) so với baseline B3 — không chỉ mùa 2010 (khó nhất).
		MultiSeason struct {
			BeatsBaselineSeasons  int `json:"beats_baseline_seasons"`
			ImprovementVsBaseline struct {
				Ci95Lower float64 `json:"ci95_lower"`
				Ci95Upper float64 `json:"ci95_upper"`
				Mean      float64 `json:"mean"`
			} `json:"improvement_vs_baseline"`
			MasePooledMean float64 `json:"mase_pooled_mean"`
			MasePooledSd   float64 `json:"mase_pooled_sd"`
			Seasons        int     `json:"seasons"`
		} `json:"multi_season"`
	} `json:"performance"`
	ReliabilityByRegion struct {
		// Bắc Độ tin cậy theo vùng (docs/07 §12.4). Bảng tĩnh gắn với phiên bản mô hình.
		Bắc Reliability `json:"Bắc"`

		// Nam Độ tin cậy theo vùng (docs/07 §12.4). Bảng tĩnh gắn với phiên bản mô hình.
		Nam Reliability `json:"Nam"`

		// Trung Độ tin cậy theo vùng (docs/07 §12.4). Bảng tĩnh gắn với phiên bản mô hình.
		Trung Reliability `json:"Trung"`
	} `json:"reliability_by_region"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ModelVersion defines model for ModelVersion.
type ModelVersion struct {
	Description string `json:"description"`

	// ModelVersion Examples: m4-r2@1.0.0
	ModelVersion      string             `json:"model_version"`
	SourceExperiments *[]string          `json:"source_experiments,omitempty"`
	Status            ModelVersionStatus `json:"status"`
}

// ModelVersionStatus defines model for ModelVersion.Status.
type ModelVersionStatus string

// Observation defines model for Observation.
type Observation struct {
	Cases float64 `json:"cases"`

	// DataSource `real` đo thật; `estimated` ước lượng small-area (2011–2025); `imputed` điền khuyết; `simulated` giả lập.
	// UI PHẢI phân biệt rõ, không để dữ liệu không-thật trông như thật (docs/10 luật T2).
	DataSource       DataSource `json:"data_source"`
	IncidencePer100k *float64   `json:"incidence_per_100k,omitempty"`

	// Month Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	Month YearMonth `json:"month"`
}

// PredictionInterval defines model for PredictionInterval.
type PredictionInterval struct {
	// Level Examples: 0.8
	Level float64 `json:"level"`
	Lower float64 `json:"lower"`

	// Method Examples: conformal_backtest_residuals
	Method string  `json:"method"`
	Upper  float64 `json:"upper"`
}

// Problem RFC 9457 problem details (docs/09 §6.3).
type Problem struct {
	// Code Mã lỗi ổn định dạng `<service>.<snake_case>` — danh mục ở contracts/errors.md.
	//
	// Examples: common.validation_error
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId string  `json:"request_id"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// Province defines model for Province.
type Province struct {
	// Name Examples: Hà Nội
	Name string `json:"name"`

	// Population Dân số tham chiếu; null nếu chưa có.
	Population *int `json:"population,omitempty"`

	// ProvinceId Examples: 01
	ProvinceId string `json:"province_id"`
	Region     Region `json:"region"`
}

// Region defines model for Region.
type Region string

// Reliability Độ tin cậy theo vùng (docs/07 §12.4). Bảng tĩnh gắn với phiên bản mô hình.
type Reliability struct {
	// NoteCode Mã ghi chú; frontend ánh xạ sang câu chữ tiếng Việt.
	//
	// Examples: bac_outbreak_years
	NoteCode    string                 `json:"note_code"`
	RegionLevel ReliabilityRegionLevel `json:"region_level"`
}

// ReliabilityRegionLevel defines model for Reliability.RegionLevel.
type ReliabilityRegionLevel string

// RiskMap defines model for RiskMap.
type RiskMap struct {
	// Horizon Tầm dự báo — số tháng tính từ tháng neo (`origin_month`).
	Horizon Horizon       `json:"horizon"`
	Items   []RiskMapItem `json:"items"`

	// Legend Ngưỡng lớp màu do server trả — frontend không tự tính (docs/10 §11.1).
	Legend struct {
		CasesPer100k []LegendClass `json:"cases_per_100k"`
		ExceedProb   []LegendClass `json:"exceed_prob"`
	} `json:"legend"`

	// Meta Provenance — bắt buộc trong mọi response chứa số liệu mô hình (docs/09 §6.5, docs/10 luật T3).
	Meta     Meta      `json:"meta"`
	Warnings []Warning `json:"warnings"`
}

// RiskMapItem defines model for RiskMapItem.
type RiskMapItem struct {
	// Forecast null nếu tỉnh không có dự báo trong lượt này.
	Forecast *ForecastItem `json:"forecast"`
	Name     string        `json:"name"`

	// OpenAlertCount null khi nguồn cảnh báo không khả dụng (kèm `warnings[]`); 0 ở Đợt 1.
	OpenAlertCount *int   `json:"open_alert_count"`
	ProvinceId     string `json:"province_id"`
	Region         Region `json:"region"`
}

// Role defines model for Role.
type Role string

// RunMode defines model for RunMode.
type RunMode string

// RunStatus defines model for RunStatus.
type RunStatus string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Số giây hiệu lực
	//
	// Examples: 900
	ExpiresIn int                    `json:"expires_in"`
	TokenType TokenResponseTokenType `json:"token_type"`
	User      User                   `json:"user"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// User defines model for User.
type User struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`

	// OrgId Đơn vị trực thuộc (CDC tỉnh / bệnh viện) — quyết định phạm vi dữ liệu được xử lý.
	OrgId    string `json:"org_id"`
	Roles    []Role `json:"roles"`
	Username string `json:"username"`
}

// Warning defines model for Warning.
type Warning struct {
	// Code Examples: gateway.alerts_unavailable
	Code    string `json:"code"`
	Message string `json:"message"`
}

// YearMonth Tháng dạng `YYYY-MM`.
//
// Examples: 2010-03
type YearMonth = string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// ProvinceId Examples: 01
type ProvinceId = string

// RunId defines model for RunId.
type RunId = openapi_types.UUID

// Conflict RFC 9457 problem details (docs/09 §6.3).
type Conflict = Problem

// Forbidden RFC 9457 problem details (docs/09 §6.3).
type Forbidden = Problem

// NotFound RFC 9457 problem details (docs/09 §6.3).
type NotFound = Problem

// TooManyRequests RFC 9457 problem details (docs/09 §6.3).
type TooManyRequests = Problem

// Unauthorized RFC 9457 problem details (docs/09 §6.3).
type Unauthorized = Problem

// ValidationError RFC 9457 problem details (docs/09 §6.3).
type ValidationError = Problem

// ListForecastRunsParams defines parameters for ListForecastRuns.
type ListForecastRunsParams struct {
	Mode   *RunMode   `form:"mode,omitempty" json:"mode,omitempty"`
	Status *RunStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit     `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Con trỏ mờ (opaque) lấy từ `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateForecastRunParams defines parameters for CreateForecastRun.
type CreateForecastRunParams struct {
	// IdempotencyKey UUID do client sinh cho mỗi lần người dùng thao tác; gửi lại cùng key trả lại đúng response cũ (24 giờ).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetProvinceGeometryParams defines parameters for GetProvinceGeometry.
type GetProvinceGeometryParams struct {
	// Version Phiên bản ranh giới; mặc định là bản mới nhất. Response có `Cache-Control` dài khi chỉ định version.
	Version *string `form:"version,omitempty" json:"version,omitempty"`
}

// ListObservationsParams defines parameters for ListObservations.
type ListObservationsParams struct {
	ProvinceId string     `form:"province_id" json:"province_id"`
	From       *YearMonth `form:"from,omitempty" json:"from,omitempty"`
	To         *YearMonth `form:"to,omitempty" json:"to,omitempty"`

	// DataVersion Mặc định là bản mới nhất.
	DataVersion *string `form:"data_version,omitempty" json:"data_version,omitempty"`
}

// GetProvinceExplanationParams defines parameters for GetProvinceExplanation.
type GetProvinceExplanationParams struct {
	RunId   *openapi_types.UUID `form:"run_id,omitempty" json:"run_id,omitempty"`
	Horizon Horizon             `form:"horizon" json:"horizon"`
}

// GetProvinceForecastsParams defines parameters for GetProvinceForecasts.
type GetProvinceForecastsParams struct {
	RunId *openapi_types.UUID `form:"run_id,omitempty" json:"run_id,omitempty"`
}

// GetRiskMapParams defines parameters for GetRiskMap.
type GetRiskMapParams struct {
	// RunId Mặc định là lượt `completed` mới nhất.
	RunId   *openapi_types.UUID `form:"run_id,omitempty" json:"run_id,omitempty"`
	Horizon Horizon             `form:"horizon" json:"horizon"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateForecastRunJSONRequestBody defines body for CreateForecastRun for application/json ContentType.
type CreateForecastRunJSONRequestBody = CreateForecastRunRequest

// Getter for additional properties for GeoJsonFeatureCollection_Features_Properties. Returns the specified
// element and whether it was found
func (a GeoJsonFeatureCollection_Features_Properties) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GeoJsonFeatureCollection_Features_Properties
func (a *GeoJsonFeatureCollection_Features_Properties) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GeoJsonFeatureCollection_Features_Properties to handle AdditionalProperties
func (a *GeoJsonFeatureCollection_Features_Properties) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["province_id"]; found {
		err = json.Unmarshal(raw, &a.ProvinceId)
		if err != nil {
			return fmt.Errorf("error reading 'province_id': %w", err)
		}
		delete(object, "province_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GeoJsonFeatureCollection_Features_Properties to handle AdditionalProperties
func (a GeoJsonFeatureCollection_Features_Properties) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["province_id"], err = json.Marshal(a.ProvinceId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'province_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Đăng nhập
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout Đăng xuất (thu hồi refresh token)
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// RefreshToken Cấp access token mới bằng refresh token trong cookie (xoay vòng)
	// (POST /auth/refresh)
	RefreshToken(c *gin.Context)
	// ListDataVersions Các phiên bản dữ liệu (panel) đã công bố
	// (GET /data-versions)
	ListDataVersions(c *gin.Context)
	// ListForecastRuns Danh sách lượt dự báo
	// (GET /forecast-runs)
	ListForecastRuns(c *gin.Context, params ListForecastRunsParams)
	// CreateForecastRun Tạo lượt dự báo (chạy nền). Vai trò tối thiểu `analyst`.
	// (POST /forecast-runs)
	CreateForecastRun(c *gin.Context, params CreateForecastRunParams)
	// GetForecastRun Chi tiết một lượt dự báo
	// (GET /forecast-runs/{run_id})
	GetForecastRun(c *gin.Context, runId RunId)
	// GetProvinceGeometry Ranh giới 34 tỉnh (GeoJSON, có phiên bản — bất biến theo `version`)
	// (GET /geo/provinces)
	GetProvinceGeometry(c *gin.Context, params GetProvinceGeometryParams)
	// GetJob Trạng thái job chạy nền (polling)
	// (GET /jobs/{job_id})
	GetJob(c *gin.Context, jobId openapi_types.UUID)
	// GetMe Người dùng hiện tại
	// (GET /me)
	GetMe(c *gin.Context)
	// GetModelCard Model card rút gọn của phiên bản mô hình đang dùng
	// (GET /model-card)
	GetModelCard(c *gin.Context)
	// ListLimitations Danh sách giới hạn đã biết (đo được) của mô hình
	// (GET /model-card/limitations)
	ListLimitations(c *gin.Context)
	// ListModelVersions Các phiên bản mô hình (danh mục đóng, trả đủ — không phân trang)
	// (GET /model-versions)
	ListModelVersions(c *gin.Context)
	// ListObservations Chuỗi quan sát theo tháng của một tỉnh
	// (GET /observations)
	ListObservations(c *gin.Context, params ListObservationsParams)
	// ListProvinces Danh mục 34 tỉnh (danh mục đóng, trả đủ — không phân trang)
	// (GET /provinces)
	ListProvinces(c *gin.Context)
	// GetProvince Chi tiết một tỉnh
	// (GET /provinces/{province_id})
	GetProvince(c *gin.Context, provinceId ProvinceId)
	// GetProvinceExplanation Yếu tố ảnh hưởng dự báo (SHAP) cho một tỉnh, một tầm dự báo
	// (GET /provinces/{province_id}/explanations)
	GetProvinceExplanation(c *gin.Context, provinceId ProvinceId, params GetProvinceExplanationParams)
	// GetProvinceForecasts Dự báo một tỉnh cho đủ các tầm dự báo của một lượt
	// (GET /provinces/{province_id}/forecasts)
	GetProvinceForecasts(c *gin.Context, provinceId ProvinceId, params GetProvinceForecastsParams)
	// GetRiskMap Bản đồ rủi ro — dự báo 34 tỉnh cho một lượt và một tầm dự báo (BFF ghép nhiều service)
	// (GET /risk-map)
	GetRiskMap(c *gin.Context, params GetRiskMapParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// ListDataVersions operation middleware
func (siw *ServerInterfaceWrapper) ListDataVersions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDataVersions(c)
}

// ListForecastRuns operation middleware
func (siw *ServerInterfaceWrapper) ListForecastRuns(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListForecastRunsParams

	// ------------- Optional query parameter "mode" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mode", c.Request.URL.Query(), &params.Mode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter mode: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListForecastRuns(c, params)
}

// CreateForecastRun operation middleware
func (siw *ServerInterfaceWrapper) CreateForecastRun(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateForecastRunParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateForecastRun(c, params)
}

// GetForecastRun operation middleware
func (siw *ServerInterfaceWrapper) GetForecastRun(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", c.Param("run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter run_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetForecastRun(c, runId)
}

// GetProvinceGeometry operation middleware
func (siw *ServerInterfaceWrapper) GetProvinceGeometry(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProvinceGeometryParams

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", c.Request.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter version: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProvinceGeometry(c, params)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJob(c, jobId)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// GetModelCard operation middleware
func (siw *ServerInterfaceWrapper) GetModelCard(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetModelCard(c)
}

// ListLimitations operation middleware
func (siw *ServerInterfaceWrapper) ListLimitations(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLimitations(c)
}

// ListModelVersions operation middleware
func (siw *ServerInterfaceWrapper) ListModelVersions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListModelVersions(c)
}

// ListObservations operation middleware
func (siw *ServerInterfaceWrapper) ListObservations(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListObservationsParams

	// ------------- Required query parameter "province_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "province_id", c.Request.URL.Query(), &params.ProvinceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter province_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "data_version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "data_version", c.Request.URL.Query(), &params.DataVersion, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter data_version: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObservations(c, params)
}

// ListProvinces operation middleware
func (siw *ServerInterfaceWrapper) ListProvinces(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProvinces(c)
}

// GetProvince operation middleware
func (siw *ServerInterfaceWrapper) GetProvince(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "province_id" -------------
	var provinceId ProvinceId

	err = runtime.BindStyledParameterWithOptions("simple", "province_id", c.Param("province_id"), &provinceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter province_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProvince(c, provinceId)
}

// GetProvinceExplanation operation middleware
func (siw *ServerInterfaceWrapper) GetProvinceExplanation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "province_id" -------------
	var provinceId ProvinceId

	err = runtime.BindStyledParameterWithOptions("simple", "province_id", c.Param("province_id"), &provinceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter province_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProvinceExplanationParams

	// ------------- Optional query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "run_id", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter run_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "horizon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "horizon", c.Request.URL.Query(), &params.Horizon, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter horizon: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProvinceExplanation(c, provinceId, params)
}

// GetProvinceForecasts operation middleware
func (siw *ServerInterfaceWrapper) GetProvinceForecasts(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "province_id" -------------
	var provinceId ProvinceId

	err = runtime.BindStyledParameterWithOptions("simple", "province_id", c.Param("province_id"), &provinceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter province_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProvinceForecastsParams

	// ------------- Optional query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "run_id", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter run_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProvinceForecasts(c, provinceId, params)
}

// GetRiskMap operation middleware
func (siw *ServerInterfaceWrapper) GetRiskMap(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRiskMapParams

	// ------------- Optional query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "run_id", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter run_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "horizon" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "horizon", c.Request.URL.Query(), &params.Horizon, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter horizon: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRiskMap(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/provinces", wrapper.ListProvinces)
	router.GET(options.BaseURL+"/provinces/:province_id", wrapper.GetProvince)
	router.GET(options.BaseURL+"/geo/provinces", wrapper.GetProvinceGeometry)
	router.GET(options.BaseURL+"/data-versions", wrapper.ListDataVersions)
	router.GET(options.BaseURL+"/observations", wrapper.ListObservations)
	router.GET(options.BaseURL+"/forecast-runs", wrapper.ListForecastRuns)
	router.POST(options.BaseURL+"/forecast-runs", wrapper.CreateForecastRun)
	router.GET(options.BaseURL+"/forecast-runs/:run_id", wrapper.GetForecastRun)
	router.GET(options.BaseURL+"/risk-map", wrapper.GetRiskMap)
	router.GET(options.BaseURL+"/provinces/:province_id/forecasts", wrapper.GetProvinceForecasts)
	router.GET(options.BaseURL+"/provinces/:province_id/explanations", wrapper.GetProvinceExplanation)
	router.GET(options.BaseURL+"/model-card", wrapper.GetModelCard)
	router.GET(options.BaseURL+"/model-card/limitations", wrapper.ListLimitations)
	router.GET(options.BaseURL+"/model-versions", wrapper.ListModelVersions)
	router.GET(options.BaseURL+"/jobs/:job_id", wrapper.GetJob)
}

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ValidationErrorApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    TokenResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse TokenResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RefreshToken401ApplicationProblemPlusJSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDataVersionsRequestObject struct {
}

type ListDataVersionsResponseObject interface {
	VisitListDataVersionsResponse(w http.ResponseWriter) error
}

type ListDataVersions200JSONResponse struct {
	Items []DataVersion `json:"items"`
}

func (response ListDataVersions200JSONResponse) VisitListDataVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDataVersions401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListDataVersions401ApplicationProblemPlusJSONResponse) VisitListDataVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListForecastRunsRequestObject struct {
	Params ListForecastRunsParams
}

type ListForecastRunsResponseObject interface {
	VisitListForecastRunsResponse(w http.ResponseWriter) error
}

type ListForecastRuns200JSONResponse struct {
	Items      []ForecastRun `json:"items"`
	NextCursor *string       `json:"next_cursor"`
}

func (response ListForecastRuns200JSONResponse) VisitListForecastRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListForecastRuns401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListForecastRuns401ApplicationProblemPlusJSONResponse) VisitListForecastRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForecastRunRequestObject struct {
	Params CreateForecastRunParams
	Body   *CreateForecastRunJSONRequestBody
}

type CreateForecastRunResponseObject interface {
	VisitCreateForecastRunResponse(w http.ResponseWriter) error
}

type CreateForecastRun202ResponseHeaders struct {
	Location *string
}

type CreateForecastRun202JSONResponse struct {
	Body    Job
	Headers CreateForecastRun202ResponseHeaders
}

func (response CreateForecastRun202JSONResponse) VisitCreateForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForecastRun400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response CreateForecastRun400ApplicationProblemPlusJSONResponse) VisitCreateForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForecastRun401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateForecastRun401ApplicationProblemPlusJSONResponse) VisitCreateForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForecastRun403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateForecastRun403ApplicationProblemPlusJSONResponse) VisitCreateForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateForecastRun409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreateForecastRun409ApplicationProblemPlusJSONResponse) VisitCreateForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetForecastRunRequestObject struct {
	RunId RunId `json:"run_id"`
}

type GetForecastRunResponseObject interface {
	VisitGetForecastRunResponse(w http.ResponseWriter) error
}

type GetForecastRun200JSONResponse ForecastRun

func (response GetForecastRun200JSONResponse) VisitGetForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetForecastRun401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetForecastRun401ApplicationProblemPlusJSONResponse) VisitGetForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetForecastRun404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetForecastRun404ApplicationProblemPlusJSONResponse) VisitGetForecastRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceGeometryRequestObject struct {
	Params GetProvinceGeometryParams
}

type GetProvinceGeometryResponseObject interface {
	VisitGetProvinceGeometryResponse(w http.ResponseWriter) error
}

type GetProvinceGeometry200ApplicationGeoPlusJSONResponse GeoJsonFeatureCollection

func (response GetProvinceGeometry200ApplicationGeoPlusJSONResponse) VisitGetProvinceGeometryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/geo+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceGeometry401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetProvinceGeometry401ApplicationProblemPlusJSONResponse) VisitGetProvinceGeometryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetJobRequestObject struct {
	JobId openapi_types.UUID `json:"job_id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse Job

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetJob401ApplicationProblemPlusJSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetJob404ApplicationProblemPlusJSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetModelCardRequestObject struct {
}

type GetModelCardResponseObject interface {
	VisitGetModelCardResponse(w http.ResponseWriter) error
}

type GetModelCard200JSONResponse ModelCard

func (response GetModelCard200JSONResponse) VisitGetModelCardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetModelCard401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetModelCard401ApplicationProblemPlusJSONResponse) VisitGetModelCardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListLimitationsRequestObject struct {
}

type ListLimitationsResponseObject interface {
	VisitListLimitationsResponse(w http.ResponseWriter) error
}

type ListLimitations200JSONResponse struct {
	Items        []Limitation `json:"items"`
	ModelVersion string       `json:"model_version"`
}

func (response ListLimitations200JSONResponse) VisitListLimitationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLimitations401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListLimitations401ApplicationProblemPlusJSONResponse) VisitListLimitationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListModelVersionsRequestObject struct {
}

type ListModelVersionsResponseObject interface {
	VisitListModelVersionsResponse(w http.ResponseWriter) error
}

type ListModelVersions200JSONResponse struct {
	Items []ModelVersion `json:"items"`
}

func (response ListModelVersions200JSONResponse) VisitListModelVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListModelVersions401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListModelVersions401ApplicationProblemPlusJSONResponse) VisitListModelVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservationsRequestObject struct {
	Params ListObservationsParams
}

type ListObservationsResponseObject interface {
	VisitListObservationsResponse(w http.ResponseWriter) error
}

type ListObservations200JSONResponse struct {
	DataVersion string        `json:"data_version"`
	Items       []Observation `json:"items"`
}

func (response ListObservations200JSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservations400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response ListObservations400ApplicationProblemPlusJSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservations401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListObservations401ApplicationProblemPlusJSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservations404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListObservations404ApplicationProblemPlusJSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListProvincesRequestObject struct {
}

type ListProvincesResponseObject interface {
	VisitListProvincesResponse(w http.ResponseWriter) error
}

type ListProvinces200JSONResponse struct {
	Items []Province `json:"items"`
}

func (response ListProvinces200JSONResponse) VisitListProvincesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProvinces401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListProvinces401ApplicationProblemPlusJSONResponse) VisitListProvincesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceRequestObject struct {
	ProvinceId ProvinceId `json:"province_id"`
}

type GetProvinceResponseObject interface {
	VisitGetProvinceResponse(w http.ResponseWriter) error
}

type GetProvince200JSONResponse Province

func (response GetProvince200JSONResponse) VisitGetProvinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvince401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetProvince401ApplicationProblemPlusJSONResponse) VisitGetProvinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvince404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetProvince404ApplicationProblemPlusJSONResponse) VisitGetProvinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceExplanationRequestObject struct {
	ProvinceId ProvinceId `json:"province_id"`
	Params     GetProvinceExplanationParams
}

type GetProvinceExplanationResponseObject interface {
	VisitGetProvinceExplanationResponse(w http.ResponseWriter) error
}

type GetProvinceExplanation200JSONResponse Explanation

func (response GetProvinceExplanation200JSONResponse) VisitGetProvinceExplanationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceExplanation401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetProvinceExplanation401ApplicationProblemPlusJSONResponse) VisitGetProvinceExplanationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceExplanation404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetProvinceExplanation404ApplicationProblemPlusJSONResponse) VisitGetProvinceExplanationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceForecastsRequestObject struct {
	ProvinceId ProvinceId `json:"province_id"`
	Params     GetProvinceForecastsParams
}

type GetProvinceForecastsResponseObject interface {
	VisitGetProvinceForecastsResponse(w http.ResponseWriter) error
}

type GetProvinceForecasts200JSONResponse struct {
	Items []ForecastItem `json:"items"`

	// Meta Provenance — bắt buộc trong mọi response chứa số liệu mô hình (docs/09 §6.5, docs/10 luật T3).
	Meta Meta `json:"meta"`
}

func (response GetProvinceForecasts200JSONResponse) VisitGetProvinceForecastsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceForecasts401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetProvinceForecasts401ApplicationProblemPlusJSONResponse) VisitGetProvinceForecastsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceForecasts404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetProvinceForecasts404ApplicationProblemPlusJSONResponse) VisitGetProvinceForecastsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRiskMapRequestObject struct {
	Params GetRiskMapParams
}

type GetRiskMapResponseObject interface {
	VisitGetRiskMapResponse(w http.ResponseWriter) error
}

type GetRiskMap200JSONResponse RiskMap

func (response GetRiskMap200JSONResponse) VisitGetRiskMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRiskMap400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response GetRiskMap400ApplicationProblemPlusJSONResponse) VisitGetRiskMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRiskMap401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetRiskMap401ApplicationProblemPlusJSONResponse) VisitGetRiskMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRiskMap404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetRiskMap404ApplicationProblemPlusJSONResponse) VisitGetRiskMapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Đăng nhập
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Đăng xuất (thu hồi refresh token)
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RefreshToken Cấp access token mới bằng refresh token trong cookie (xoay vòng)
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// ListDataVersions Các phiên bản dữ liệu (panel) đã công bố
	// (GET /data-versions)
	ListDataVersions(ctx context.Context, request ListDataVersionsRequestObject) (ListDataVersionsResponseObject, error)
	// ListForecastRuns Danh sách lượt dự báo
	// (GET /forecast-runs)
	ListForecastRuns(ctx context.Context, request ListForecastRunsRequestObject) (ListForecastRunsResponseObject, error)
	// CreateForecastRun Tạo lượt dự báo (chạy nền). Vai trò tối thiểu `analyst`.
	// (POST /forecast-runs)
	CreateForecastRun(ctx context.Context, request CreateForecastRunRequestObject) (CreateForecastRunResponseObject, error)
	// GetForecastRun Chi tiết một lượt dự báo
	// (GET /forecast-runs/{run_id})
	GetForecastRun(ctx context.Context, request GetForecastRunRequestObject) (GetForecastRunResponseObject, error)
	// GetProvinceGeometry Ranh giới 34 tỉnh (GeoJSON, có phiên bản — bất biến theo `version`)
	// (GET /geo/provinces)
	GetProvinceGeometry(ctx context.Context, request GetProvinceGeometryRequestObject) (GetProvinceGeometryResponseObject, error)
	// GetJob Trạng thái job chạy nền (polling)
	// (GET /jobs/{job_id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// GetMe Người dùng hiện tại
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// GetModelCard Model card rút gọn của phiên bản mô hình đang dùng
	// (GET /model-card)
	GetModelCard(ctx context.Context, request GetModelCardRequestObject) (GetModelCardResponseObject, error)
	// ListLimitations Danh sách giới hạn đã biết (đo được) của mô hình
	// (GET /model-card/limitations)
	ListLimitations(ctx context.Context, request ListLimitationsRequestObject) (ListLimitationsResponseObject, error)
	// ListModelVersions Các phiên bản mô hình (danh mục đóng, trả đủ — không phân trang)
	// (GET /model-versions)
	ListModelVersions(ctx context.Context, request ListModelVersionsRequestObject) (ListModelVersionsResponseObject, error)
	// ListObservations Chuỗi quan sát theo tháng của một tỉnh
	// (GET /observations)
	ListObservations(ctx context.Context, request ListObservationsRequestObject) (ListObservationsResponseObject, error)
	// ListProvinces Danh mục 34 tỉnh (danh mục đóng, trả đủ — không phân trang)
	// (GET /provinces)
	ListProvinces(ctx context.Context, request ListProvincesRequestObject) (ListProvincesResponseObject, error)
	// GetProvince Chi tiết một tỉnh
	// (GET /provinces/{province_id})
	GetProvince(ctx context.Context, request GetProvinceRequestObject) (GetProvinceResponseObject, error)
	// GetProvinceExplanation Yếu tố ảnh hưởng dự báo (SHAP) cho một tỉnh, một tầm dự báo
	// (GET /provinces/{province_id}/explanations)
	GetProvinceExplanation(ctx context.Context, request GetProvinceExplanationRequestObject) (GetProvinceExplanationResponseObject, error)
	// GetProvinceForecasts Dự báo một tỉnh cho đủ các tầm dự báo của một lượt
	// (GET /provinces/{province_id}/forecasts)
	GetProvinceForecasts(ctx context.Context, request GetProvinceForecastsRequestObject) (GetProvinceForecastsResponseObject, error)
	// GetRiskMap Bản đồ rủi ro — dự báo 34 tỉnh cho một lượt và một tầm dự báo (BFF ghép nhiều service)
	// (GET /risk-map)
	GetRiskMap(ctx context.Context, request GetRiskMapRequestObject) (GetRiskMapResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *gin.Context) {
	var request RefreshTokenRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDataVersions operation middleware
func (sh *strictHandler) ListDataVersions(ctx *gin.Context) {
	var request ListDataVersionsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListDataVersions(ctx, request.(ListDataVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDataVersions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListDataVersionsResponseObject); ok {
		if err := validResponse.VisitListDataVersionsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListForecastRuns operation middleware
func (sh *strictHandler) ListForecastRuns(ctx *gin.Context, params ListForecastRunsParams) {
	var request ListForecastRunsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListForecastRuns(ctx, request.(ListForecastRunsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListForecastRuns")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListForecastRunsResponseObject); ok {
		if err := validResponse.VisitListForecastRunsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateForecastRun operation middleware
func (sh *strictHandler) CreateForecastRun(ctx *gin.Context, params CreateForecastRunParams) {
	var request CreateForecastRunRequestObject

	request.Params = params

	var body CreateForecastRunJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateForecastRun(ctx, request.(CreateForecastRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateForecastRun")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateForecastRunResponseObject); ok {
		if err := validResponse.VisitCreateForecastRunResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetForecastRun operation middleware
func (sh *strictHandler) GetForecastRun(ctx *gin.Context, runId RunId) {
	var request GetForecastRunRequestObject

	request.RunId = runId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetForecastRun(ctx, request.(GetForecastRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetForecastRun")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetForecastRunResponseObject); ok {
		if err := validResponse.VisitGetForecastRunResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvinceGeometry operation middleware
func (sh *strictHandler) GetProvinceGeometry(ctx *gin.Context, params GetProvinceGeometryParams) {
	var request GetProvinceGeometryRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvinceGeometry(ctx, request.(GetProvinceGeometryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvinceGeometry")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProvinceGeometryResponseObject); ok {
		if err := validResponse.VisitGetProvinceGeometryResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(ctx *gin.Context, jobId openapi_types.UUID) {
	var request GetJobRequestObject

	request.JobId = jobId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *gin.Context) {
	var request GetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetModelCard operation middleware
func (sh *strictHandler) GetModelCard(ctx *gin.Context) {
	var request GetModelCardRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetModelCard(ctx, request.(GetModelCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetModelCard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetModelCardResponseObject); ok {
		if err := validResponse.VisitGetModelCardResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLimitations operation middleware
func (sh *strictHandler) ListLimitations(ctx *gin.Context) {
	var request ListLimitationsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListLimitations(ctx, request.(ListLimitationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLimitations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListLimitationsResponseObject); ok {
		if err := validResponse.VisitListLimitationsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListModelVersions operation middleware
func (sh *strictHandler) ListModelVersions(ctx *gin.Context) {
	var request ListModelVersionsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListModelVersions(ctx, request.(ListModelVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListModelVersions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListModelVersionsResponseObject); ok {
		if err := validResponse.VisitListModelVersionsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListObservations operation middleware
func (sh *strictHandler) ListObservations(ctx *gin.Context, params ListObservationsParams) {
	var request ListObservationsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListObservations(ctx, request.(ListObservationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListObservations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListObservationsResponseObject); ok {
		if err := validResponse.VisitListObservationsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProvinces operation middleware
func (sh *strictHandler) ListProvinces(ctx *gin.Context) {
	var request ListProvincesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProvinces(ctx, request.(ListProvincesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProvinces")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListProvincesResponseObject); ok {
		if err := validResponse.VisitListProvincesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvince operation middleware
func (sh *strictHandler) GetProvince(ctx *gin.Context, provinceId ProvinceId) {
	var request GetProvinceRequestObject

	request.ProvinceId = provinceId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvince(ctx, request.(GetProvinceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvince")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProvinceResponseObject); ok {
		if err := validResponse.VisitGetProvinceResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvinceExplanation operation middleware
func (sh *strictHandler) GetProvinceExplanation(ctx *gin.Context, provinceId ProvinceId, params GetProvinceExplanationParams) {
	var request GetProvinceExplanationRequestObject

	request.ProvinceId = provinceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvinceExplanation(ctx, request.(GetProvinceExplanationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvinceExplanation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProvinceExplanationResponseObject); ok {
		if err := validResponse.VisitGetProvinceExplanationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvinceForecasts operation middleware
func (sh *strictHandler) GetProvinceForecasts(ctx *gin.Context, provinceId ProvinceId, params GetProvinceForecastsParams) {
	var request GetProvinceForecastsRequestObject

	request.ProvinceId = provinceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvinceForecasts(ctx, request.(GetProvinceForecastsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvinceForecasts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProvinceForecastsResponseObject); ok {
		if err := validResponse.VisitGetProvinceForecastsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRiskMap operation middleware
func (sh *strictHandler) GetRiskMap(ctx *gin.Context, params GetRiskMapParams) {
	var request GetRiskMapRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRiskMap(ctx, request.(GetRiskMapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRiskMap")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetRiskMapResponseObject); ok {
		if err := validResponse.VisitGetRiskMapResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
