// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DataSource.
const (
	Estimated DataSource = "estimated"
	Imputed   DataSource = "imputed"
	Real      DataSource = "real"
	Simulated DataSource = "simulated"
)

// Valid indicates whether the value is a known member of the DataSource enum.
func (e DataSource) Valid() bool {
	switch e {
	case Estimated:
		return true
	case Imputed:
		return true
	case Real:
		return true
	case Simulated:
		return true
	default:
		return false
	}
}

// Defines values for GeoJsonFeatureCollectionFeaturesType.
const (
	Feature GeoJsonFeatureCollectionFeaturesType = "Feature"
)

// Valid indicates whether the value is a known member of the GeoJsonFeatureCollectionFeaturesType enum.
func (e GeoJsonFeatureCollectionFeaturesType) Valid() bool {
	switch e {
	case Feature:
		return true
	default:
		return false
	}
}

// Defines values for GeoJsonFeatureCollectionType.
const (
	FeatureCollection GeoJsonFeatureCollectionType = "FeatureCollection"
)

// Valid indicates whether the value is a known member of the GeoJsonFeatureCollectionType enum.
func (e GeoJsonFeatureCollectionType) Valid() bool {
	switch e {
	case FeatureCollection:
		return true
	default:
		return false
	}
}

// Defines values for Region.
const (
	Bắc   Region = "Bắc"
	Nam   Region = "Nam"
	Trung Region = "Trung"
)

// Valid indicates whether the value is a known member of the Region enum.
func (e Region) Valid() bool {
	switch e {
	case Bắc:
		return true
	case Nam:
		return true
	case Trung:
		return true
	default:
		return false
	}
}

// Defines values for Healthz200JSONResponseBodyStatus.
const (
	Ok Healthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the Healthz200JSONResponseBodyStatus enum.
func (e Healthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Readyz200JSONResponseBodyStatus.
const (
	Ready Readyz200JSONResponseBodyStatus = "ready"
)

// Valid indicates whether the value is a known member of the Readyz200JSONResponseBodyStatus enum.
func (e Readyz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// CreateDataVersionRequest defines model for CreateDataVersionRequest.
type CreateDataVersionRequest struct {
	// Manifest JSON của PanelManifest (dạng chuỗi trong multipart).
	Manifest openapi_types.File `json:"manifest"`

	// Panel File panel_monthly.parquet.
	Panel openapi_types.File `json:"panel"`
}

// DataSource `real` đo thật; `estimated` ước lượng small-area (2011–2025); `imputed` điền khuyết; `simulated` giả lập.
// UI PHẢI phân biệt rõ, không để dữ liệu không-thật trông như thật (docs/10 luật T2).
type DataSource string

// DataVersion defines model for DataVersion.
type DataVersion struct {
	// FirstMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	FirstMonth *YearMonth `json:"first_month,omitempty"`

	// LastMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	LastMonth   *YearMonth `json:"last_month,omitempty"`
	PublishedAt time.Time  `json:"published_at"`

	// RealShare Tỉ lệ dòng dữ liệu `real` trong phiên bản.
	RealShare float64 `json:"real_share"`

	// Version Examples: v0.2.0
	Version string `json:"version"`
}

// DataVersionDetail DataVersion kèm siêu dữ liệu đầy đủ.
type DataVersionDetail struct {
	// FirstMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	FirstMonth  *YearMonth `json:"first_month,omitempty"`
	KnownIssues *[]string  `json:"known_issues,omitempty"`

	// LastMonth Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	LastMonth   *YearMonth `json:"last_month,omitempty"`
	NProvinces  int        `json:"n_provinces"`
	NRows       int        `json:"n_rows"`
	PublishedAt time.Time  `json:"published_at"`
	RealShare   float64    `json:"real_share"`
	Sha256      string     `json:"sha256"`

	// Version Examples: v0.2.0
	Version string `json:"version"`
}

// DataVersionId Tên phiên bản dữ liệu (thư mục `data/processed/vX.Y.Z` của ai-service).
//
// Examples: v0.2.0
type DataVersionId = string

// GeoJsonFeatureCollection defines model for GeoJsonFeatureCollection.
type GeoJsonFeatureCollection struct {
	Features []struct {
		Geometry   map[string]interface{}                       `json:"geometry"`
		Properties GeoJsonFeatureCollection_Features_Properties `json:"properties"`
		Type       GeoJsonFeatureCollectionFeaturesType         `json:"type"`
	} `json:"features"`
	Type GeoJsonFeatureCollectionType `json:"type"`
}

// GeoJsonFeatureCollection_Features_Properties defines model for GeoJsonFeatureCollection.Features.Properties.
type GeoJsonFeatureCollection_Features_Properties struct {
	// ProvinceId Mã tỉnh (34 tỉnh mới) — slug không dấu, khớp `new_province_code` trong ai-service/data/external/province_metadata.csv.
	//
	// Examples: ho_chi_minh
	ProvinceId           ProvinceId             `json:"province_id"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GeoJsonFeatureCollectionFeaturesType defines model for GeoJsonFeatureCollection.Features.Type.
type GeoJsonFeatureCollectionFeaturesType string

// GeoJsonFeatureCollectionType defines model for GeoJsonFeatureCollection.Type.
type GeoJsonFeatureCollectionType string

// Observation defines model for Observation.
type Observation struct {
	Cases float64 `json:"cases"`

	// DataSource `real` đo thật; `estimated` ước lượng small-area (2011–2025); `imputed` điền khuyết; `simulated` giả lập.
	// UI PHẢI phân biệt rõ, không để dữ liệu không-thật trông như thật (docs/10 luật T2).
	DataSource       DataSource `json:"data_source"`
	IncidencePer100k *float64   `json:"incidence_per_100k,omitempty"`

	// Month Tháng dạng `YYYY-MM`.
	//
	// Examples: 2010-03
	Month YearMonth `json:"month"`
}

// Problem RFC 9457 problem details (docs/09 §6.3).
type Problem struct {
	// Code Mã lỗi ổn định dạng `<service>.<snake_case>` — danh mục ở contracts/errors.md.
	//
	// Examples: common.validation_error
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId string  `json:"request_id"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// Province defines model for Province.
type Province struct {
	// Name Examples: Hồ Chí Minh
	Name string `json:"name"`

	// Population Dân số tham chiếu; null nếu chưa có.
	Population *int `json:"population,omitempty"`

	// ProvinceId Mã tỉnh (34 tỉnh mới) — slug không dấu, khớp `new_province_code` trong ai-service/data/external/province_metadata.csv.
	//
	// Examples: ho_chi_minh
	ProvinceId ProvinceId `json:"province_id"`
	Region     Region     `json:"region"`
}

// ProvinceId Mã tỉnh (34 tỉnh mới) — slug không dấu, khớp `new_province_code` trong ai-service/data/external/province_metadata.csv.
//
// Examples: ho_chi_minh
type ProvinceId = string

// Region defines model for Region.
type Region string

// YearMonth Tháng dạng `YYYY-MM`.
//
// Examples: 2010-03
type YearMonth = string

// ActorId defines model for ActorId.
type ActorId = string

// ActorOrg defines model for ActorOrg.
type ActorOrg = string

// ActorRoles defines model for ActorRoles.
type ActorRoles = string

// DataVersionPath Tên phiên bản dữ liệu (thư mục `data/processed/vX.Y.Z` của ai-service).
//
// Examples: v0.2.0
type DataVersionPath = DataVersionId

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// ProvinceIdPath Mã tỉnh (34 tỉnh mới) — slug không dấu, khớp `new_province_code` trong ai-service/data/external/province_metadata.csv.
//
// Examples: ho_chi_minh
type ProvinceIdPath = ProvinceId

// Conflict RFC 9457 problem details (docs/09 §6.3).
type Conflict = Problem

// Forbidden RFC 9457 problem details (docs/09 §6.3).
type Forbidden = Problem

// NotFound RFC 9457 problem details (docs/09 §6.3).
type NotFound = Problem

// Unauthenticated RFC 9457 problem details (docs/09 §6.3).
type Unauthenticated = Problem

// Unavailable RFC 9457 problem details (docs/09 §6.3).
type Unavailable = Problem

// ValidationError RFC 9457 problem details (docs/09 §6.3).
type ValidationError = Problem

// Healthz200JSONResponseBodyStatus defines parameters for Healthz.
type Healthz200JSONResponseBodyStatus string

// CreateDataVersionParams defines parameters for CreateDataVersion.
type CreateDataVersionParams struct {
	// IdempotencyKey UUID cho mỗi lần thao tác; gửi lại cùng key trả lại đúng response cũ (24 giờ). Xem docs/09 §6.6.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// XActorID ID người dùng gốc do gateway gắn sau khi xác minh JWT. CHỈ được tin khi đi kèm token dịch vụ hợp lệ.
	XActorID ActorId `json:"X-Actor-ID"`

	// XActorRoles Vai trò của người dùng gốc, ngăn cách bằng dấu phẩy (vd `viewer,analyst`).
	XActorRoles ActorRoles `json:"X-Actor-Roles"`

	// XOrgID Đơn vị trực thuộc của người dùng gốc (quyết định phạm vi dữ liệu).
	XOrgID *ActorOrg `json:"X-Org-ID,omitempty"`
}

// GetProvinceGeometryParams defines parameters for GetProvinceGeometry.
type GetProvinceGeometryParams struct {
	// Version Mặc định là bản mới nhất. Mã lỗi `surveillance.geometry_version_not_found` nếu không có.
	Version *string `form:"version,omitempty" json:"version,omitempty"`
}

// ListObservationsParams defines parameters for ListObservations.
type ListObservationsParams struct {
	ProvinceId ProvinceId `form:"province_id" json:"province_id"`
	From       *YearMonth `form:"from,omitempty" json:"from,omitempty"`
	To         *YearMonth `form:"to,omitempty" json:"to,omitempty"`

	// DataVersion Mặc định là bản mới nhất.
	DataVersion *DataVersionId `form:"data_version,omitempty" json:"data_version,omitempty"`
}

// Readyz200JSONResponseBodyStatus defines parameters for Readyz.
type Readyz200JSONResponseBodyStatus string

// CreateDataVersionMultipartRequestBody defines body for CreateDataVersion for multipart/form-data ContentType.
type CreateDataVersionMultipartRequestBody = CreateDataVersionRequest

// Getter for additional properties for GeoJsonFeatureCollection_Features_Properties. Returns the specified
// element and whether it was found
func (a GeoJsonFeatureCollection_Features_Properties) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GeoJsonFeatureCollection_Features_Properties
func (a *GeoJsonFeatureCollection_Features_Properties) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GeoJsonFeatureCollection_Features_Properties to handle AdditionalProperties
func (a *GeoJsonFeatureCollection_Features_Properties) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["province_id"]; found {
		err = json.Unmarshal(raw, &a.ProvinceId)
		if err != nil {
			return fmt.Errorf("error reading 'province_id': %w", err)
		}
		delete(object, "province_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GeoJsonFeatureCollection_Features_Properties to handle AdditionalProperties
func (a GeoJsonFeatureCollection_Features_Properties) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["province_id"], err = json.Marshal(a.ProvinceId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'province_id': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthz Tiến trình còn sống (không kiểm phụ thuộc)
	// (GET /healthz)
	Healthz(c *gin.Context)
	// ListDataVersions Các phiên bản dữ liệu (panel) đã công bố
	// (GET /internal/v1/data-versions)
	ListDataVersions(c *gin.Context)
	// CreateDataVersion Nhập một phiên bản dữ liệu (panel) mới. Yêu cầu vai trò `data_manager`.
	// (POST /internal/v1/data-versions)
	CreateDataVersion(c *gin.Context, params CreateDataVersionParams)
	// GetDataVersion Chi tiết một phiên bản dữ liệu
	// (GET /internal/v1/data-versions/{version})
	GetDataVersion(c *gin.Context, version DataVersionPath)
	// DownloadPanel Tải panel (Parquet) của một phiên bản — nguồn dữ liệu của `forecast`
	// (GET /internal/v1/data-versions/{version}/panel)
	DownloadPanel(c *gin.Context, version DataVersionPath)
	// GetProvinceGeometry Ranh giới 34 tỉnh (GeoJSON, có phiên bản, bất biến theo `version`)
	// (GET /internal/v1/geo/provinces)
	GetProvinceGeometry(c *gin.Context, params GetProvinceGeometryParams)
	// ListObservations Chuỗi quan sát theo tháng của một tỉnh
	// (GET /internal/v1/observations)
	ListObservations(c *gin.Context, params ListObservationsParams)
	// ListProvinces Danh mục 34 tỉnh (danh mục đóng, trả đủ — không phân trang)
	// (GET /internal/v1/provinces)
	ListProvinces(c *gin.Context)
	// GetProvince Chi tiết một tỉnh
	// (GET /internal/v1/provinces/{province_id})
	GetProvince(c *gin.Context, provinceId ProvinceIdPath)
	// Readyz Sẵn sàng nhận tải (đã kiểm phụ thuộc)
	// (GET /readyz)
	Readyz(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// ListDataVersions operation middleware
func (siw *ServerInterfaceWrapper) ListDataVersions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDataVersions(c)
}

// CreateDataVersion operation middleware
func (siw *ServerInterfaceWrapper) CreateDataVersion(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDataVersionParams

	headers := c.Request.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Idempotency-Key, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Idempotency-Key: %w", err), http.StatusBadRequest)
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter Idempotency-Key is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Actor-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Actor-ID")]; found {
		var XActorID ActorId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Actor-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Actor-ID", valueList[0], &XActorID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Actor-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XActorID = XActorID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Actor-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Actor-Roles" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Actor-Roles")]; found {
		var XActorRoles ActorRoles
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Actor-Roles, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Actor-Roles", valueList[0], &XActorRoles, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Actor-Roles: %w", err), http.StatusBadRequest)
			return
		}

		params.XActorRoles = XActorRoles

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Actor-Roles is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Org-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Org-ID")]; found {
		var XOrgID ActorOrg
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Org-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Org-ID", valueList[0], &XOrgID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Org-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XOrgID = &XOrgID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDataVersion(c, params)
}

// GetDataVersion operation middleware
func (siw *ServerInterfaceWrapper) GetDataVersion(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "version" -------------
	var version DataVersionPath

	err = runtime.BindStyledParameterWithOptions("simple", "version", c.Param("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter version: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDataVersion(c, version)
}

// DownloadPanel operation middleware
func (siw *ServerInterfaceWrapper) DownloadPanel(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "version" -------------
	var version DataVersionPath

	err = runtime.BindStyledParameterWithOptions("simple", "version", c.Param("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter version: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DownloadPanel(c, version)
}

// GetProvinceGeometry operation middleware
func (siw *ServerInterfaceWrapper) GetProvinceGeometry(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProvinceGeometryParams

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", c.Request.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter version: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProvinceGeometry(c, params)
}

// ListObservations operation middleware
func (siw *ServerInterfaceWrapper) ListObservations(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListObservationsParams

	// ------------- Required query parameter "province_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "province_id", c.Request.URL.Query(), &params.ProvinceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter province_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "data_version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "data_version", c.Request.URL.Query(), &params.DataVersion, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter data_version: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObservations(c, params)
}

// ListProvinces operation middleware
func (siw *ServerInterfaceWrapper) ListProvinces(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProvinces(c)
}

// GetProvince operation middleware
func (siw *ServerInterfaceWrapper) GetProvince(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "province_id" -------------
	var provinceId ProvinceIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "province_id", c.Param("province_id"), &provinceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter province_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProvince(c, provinceId)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Readyz(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/internal/v1/provinces", wrapper.ListProvinces)
	router.GET(options.BaseURL+"/internal/v1/provinces/:province_id", wrapper.GetProvince)
	router.GET(options.BaseURL+"/internal/v1/geo/provinces", wrapper.GetProvinceGeometry)
	router.GET(options.BaseURL+"/internal/v1/data-versions", wrapper.ListDataVersions)
	router.POST(options.BaseURL+"/internal/v1/data-versions", wrapper.CreateDataVersion)
	router.GET(options.BaseURL+"/internal/v1/data-versions/:version", wrapper.GetDataVersion)
	router.GET(options.BaseURL+"/internal/v1/data-versions/:version/panel", wrapper.DownloadPanel)
	router.GET(options.BaseURL+"/internal/v1/observations", wrapper.ListObservations)
	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/readyz", wrapper.Readyz)
}

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnauthenticatedApplicationProblemPlusJSONResponse Problem

type UnavailableApplicationProblemPlusJSONResponse Problem

type ValidationErrorApplicationProblemPlusJSONResponse Problem

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse struct {
	Status Healthz200JSONResponseBodyStatus `json:"status"`
}

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Healthz500ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response Healthz500ApplicationProblemPlusJSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListDataVersionsRequestObject struct {
}

type ListDataVersionsResponseObject interface {
	VisitListDataVersionsResponse(w http.ResponseWriter) error
}

type ListDataVersions200JSONResponse struct {
	Items []DataVersion `json:"items"`
}

func (response ListDataVersions200JSONResponse) VisitListDataVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDataVersions401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response ListDataVersions401ApplicationProblemPlusJSONResponse) VisitListDataVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDataVersions503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response ListDataVersions503ApplicationProblemPlusJSONResponse) VisitListDataVersionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDataVersionRequestObject struct {
	Params CreateDataVersionParams
	Body   *multipart.Reader
}

type CreateDataVersionResponseObject interface {
	VisitCreateDataVersionResponse(w http.ResponseWriter) error
}

type CreateDataVersion201JSONResponse DataVersionDetail

func (response CreateDataVersion201JSONResponse) VisitCreateDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDataVersion400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response CreateDataVersion400ApplicationProblemPlusJSONResponse) VisitCreateDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDataVersion401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response CreateDataVersion401ApplicationProblemPlusJSONResponse) VisitCreateDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDataVersion403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateDataVersion403ApplicationProblemPlusJSONResponse) VisitCreateDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDataVersion409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CreateDataVersion409ApplicationProblemPlusJSONResponse) VisitCreateDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateDataVersion503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response CreateDataVersion503ApplicationProblemPlusJSONResponse) VisitCreateDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetDataVersionRequestObject struct {
	Version DataVersionPath `json:"version"`
}

type GetDataVersionResponseObject interface {
	VisitGetDataVersionResponse(w http.ResponseWriter) error
}

type GetDataVersion200JSONResponse DataVersionDetail

func (response GetDataVersion200JSONResponse) VisitGetDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDataVersion401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetDataVersion401ApplicationProblemPlusJSONResponse) VisitGetDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDataVersion404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDataVersion404ApplicationProblemPlusJSONResponse) VisitGetDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDataVersion503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetDataVersion503ApplicationProblemPlusJSONResponse) VisitGetDataVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadPanelRequestObject struct {
	Version DataVersionPath `json:"version"`
}

type DownloadPanelResponseObject interface {
	VisitDownloadPanelResponse(w http.ResponseWriter) error
}

type DownloadPanel200ResponseHeaders struct {
	XContentSHA256 *string
}

type DownloadPanel200ApplicationvndApacheParquetResponse struct {
	Body          io.Reader
	Headers       DownloadPanel200ResponseHeaders
	ContentLength int64
}

func (response DownloadPanel200ApplicationvndApacheParquetResponse) VisitDownloadPanelResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/vnd.apache.parquet")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.XContentSHA256 != nil {
		w.Header().Set("X-Content-SHA256", fmt.Sprint(*response.Headers.XContentSHA256))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadPanel401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response DownloadPanel401ApplicationProblemPlusJSONResponse) VisitDownloadPanelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadPanel404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DownloadPanel404ApplicationProblemPlusJSONResponse) VisitDownloadPanelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadPanel503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response DownloadPanel503ApplicationProblemPlusJSONResponse) VisitDownloadPanelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceGeometryRequestObject struct {
	Params GetProvinceGeometryParams
}

type GetProvinceGeometryResponseObject interface {
	VisitGetProvinceGeometryResponse(w http.ResponseWriter) error
}

type GetProvinceGeometry200ApplicationGeoPlusJSONResponse GeoJsonFeatureCollection

func (response GetProvinceGeometry200ApplicationGeoPlusJSONResponse) VisitGetProvinceGeometryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/geo+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceGeometry401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetProvinceGeometry401ApplicationProblemPlusJSONResponse) VisitGetProvinceGeometryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceGeometry404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetProvinceGeometry404ApplicationProblemPlusJSONResponse) VisitGetProvinceGeometryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceGeometry503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetProvinceGeometry503ApplicationProblemPlusJSONResponse) VisitGetProvinceGeometryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservationsRequestObject struct {
	Params ListObservationsParams
}

type ListObservationsResponseObject interface {
	VisitListObservationsResponse(w http.ResponseWriter) error
}

type ListObservations200JSONResponse struct {
	// DataVersion Tên phiên bản dữ liệu (thư mục `data/processed/vX.Y.Z` của ai-service).
	//
	// Examples: v0.2.0
	DataVersion DataVersionId `json:"data_version"`
	Items       []Observation `json:"items"`
}

func (response ListObservations200JSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservations400ApplicationProblemPlusJSONResponse struct {
	ValidationErrorApplicationProblemPlusJSONResponse
}

func (response ListObservations400ApplicationProblemPlusJSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservations401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response ListObservations401ApplicationProblemPlusJSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservations404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListObservations404ApplicationProblemPlusJSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListObservations503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response ListObservations503ApplicationProblemPlusJSONResponse) VisitListObservationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListProvincesRequestObject struct {
}

type ListProvincesResponseObject interface {
	VisitListProvincesResponse(w http.ResponseWriter) error
}

type ListProvinces200JSONResponse struct {
	Items []Province `json:"items"`
}

func (response ListProvinces200JSONResponse) VisitListProvincesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProvinces401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response ListProvinces401ApplicationProblemPlusJSONResponse) VisitListProvincesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProvinces503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response ListProvinces503ApplicationProblemPlusJSONResponse) VisitListProvincesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvinceRequestObject struct {
	ProvinceId ProvinceIdPath `json:"province_id"`
}

type GetProvinceResponseObject interface {
	VisitGetProvinceResponse(w http.ResponseWriter) error
}

type GetProvince200JSONResponse Province

func (response GetProvince200JSONResponse) VisitGetProvinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvince401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetProvince401ApplicationProblemPlusJSONResponse) VisitGetProvinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvince404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetProvince404ApplicationProblemPlusJSONResponse) VisitGetProvinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvince503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response GetProvince503ApplicationProblemPlusJSONResponse) VisitGetProvinceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200JSONResponse struct {
	Status Readyz200JSONResponseBodyStatus `json:"status"`
}

func (response Readyz200JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Readyz503ApplicationProblemPlusJSONResponse struct {
	UnavailableApplicationProblemPlusJSONResponse
}

func (response Readyz503ApplicationProblemPlusJSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Healthz Tiến trình còn sống (không kiểm phụ thuộc)
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// ListDataVersions Các phiên bản dữ liệu (panel) đã công bố
	// (GET /internal/v1/data-versions)
	ListDataVersions(ctx context.Context, request ListDataVersionsRequestObject) (ListDataVersionsResponseObject, error)
	// CreateDataVersion Nhập một phiên bản dữ liệu (panel) mới. Yêu cầu vai trò `data_manager`.
	// (POST /internal/v1/data-versions)
	CreateDataVersion(ctx context.Context, request CreateDataVersionRequestObject) (CreateDataVersionResponseObject, error)
	// GetDataVersion Chi tiết một phiên bản dữ liệu
	// (GET /internal/v1/data-versions/{version})
	GetDataVersion(ctx context.Context, request GetDataVersionRequestObject) (GetDataVersionResponseObject, error)
	// DownloadPanel Tải panel (Parquet) của một phiên bản — nguồn dữ liệu của `forecast`
	// (GET /internal/v1/data-versions/{version}/panel)
	DownloadPanel(ctx context.Context, request DownloadPanelRequestObject) (DownloadPanelResponseObject, error)
	// GetProvinceGeometry Ranh giới 34 tỉnh (GeoJSON, có phiên bản, bất biến theo `version`)
	// (GET /internal/v1/geo/provinces)
	GetProvinceGeometry(ctx context.Context, request GetProvinceGeometryRequestObject) (GetProvinceGeometryResponseObject, error)
	// ListObservations Chuỗi quan sát theo tháng của một tỉnh
	// (GET /internal/v1/observations)
	ListObservations(ctx context.Context, request ListObservationsRequestObject) (ListObservationsResponseObject, error)
	// ListProvinces Danh mục 34 tỉnh (danh mục đóng, trả đủ — không phân trang)
	// (GET /internal/v1/provinces)
	ListProvinces(ctx context.Context, request ListProvincesRequestObject) (ListProvincesResponseObject, error)
	// GetProvince Chi tiết một tỉnh
	// (GET /internal/v1/provinces/{province_id})
	GetProvince(ctx context.Context, request GetProvinceRequestObject) (GetProvinceResponseObject, error)
	// Readyz Sẵn sàng nhận tải (đã kiểm phụ thuộc)
	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(ctx *gin.Context) {
	var request HealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDataVersions operation middleware
func (sh *strictHandler) ListDataVersions(ctx *gin.Context) {
	var request ListDataVersionsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListDataVersions(ctx, request.(ListDataVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDataVersions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListDataVersionsResponseObject); ok {
		if err := validResponse.VisitListDataVersionsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDataVersion operation middleware
func (sh *strictHandler) CreateDataVersion(ctx *gin.Context, params CreateDataVersionParams) {
	var request CreateDataVersionRequestObject

	request.Params = params

	if reader, err := ctx.Request.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDataVersion(ctx, request.(CreateDataVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDataVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateDataVersionResponseObject); ok {
		if err := validResponse.VisitCreateDataVersionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDataVersion operation middleware
func (sh *strictHandler) GetDataVersion(ctx *gin.Context, version DataVersionPath) {
	var request GetDataVersionRequestObject

	request.Version = version

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDataVersion(ctx, request.(GetDataVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDataVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetDataVersionResponseObject); ok {
		if err := validResponse.VisitGetDataVersionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadPanel operation middleware
func (sh *strictHandler) DownloadPanel(ctx *gin.Context, version DataVersionPath) {
	var request DownloadPanelRequestObject

	request.Version = version

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadPanel(ctx, request.(DownloadPanelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadPanel")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DownloadPanelResponseObject); ok {
		if err := validResponse.VisitDownloadPanelResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvinceGeometry operation middleware
func (sh *strictHandler) GetProvinceGeometry(ctx *gin.Context, params GetProvinceGeometryParams) {
	var request GetProvinceGeometryRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvinceGeometry(ctx, request.(GetProvinceGeometryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvinceGeometry")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProvinceGeometryResponseObject); ok {
		if err := validResponse.VisitGetProvinceGeometryResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListObservations operation middleware
func (sh *strictHandler) ListObservations(ctx *gin.Context, params ListObservationsParams) {
	var request ListObservationsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListObservations(ctx, request.(ListObservationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListObservations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListObservationsResponseObject); ok {
		if err := validResponse.VisitListObservationsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProvinces operation middleware
func (sh *strictHandler) ListProvinces(ctx *gin.Context) {
	var request ListProvincesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProvinces(ctx, request.(ListProvincesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProvinces")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListProvincesResponseObject); ok {
		if err := validResponse.VisitListProvincesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvince operation middleware
func (sh *strictHandler) GetProvince(ctx *gin.Context, provinceId ProvinceIdPath) {
	var request GetProvinceRequestObject

	request.ProvinceId = provinceId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvince(ctx, request.(GetProvinceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvince")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProvinceResponseObject); ok {
		if err := validResponse.VisitGetProvinceResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(ctx *gin.Context) {
	var request ReadyzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx, request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		if err := validResponse.VisitReadyzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
