/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cấp access token mới bằng refresh token trong cookie (xoay vòng) */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất (thu hồi refresh token) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Người dùng hiện tại */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh mục 34 tỉnh (danh mục đóng, trả đủ — không phân trang) */
        get: operations["listProvinces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provinces/{province_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết một tỉnh */
        get: operations["getProvince"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranh giới 34 tỉnh (GeoJSON, có phiên bản — bất biến theo `version`) */
        get: operations["getProvinceGeometry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Các phiên bản dữ liệu (panel) đã công bố */
        get: operations["listDataVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chuỗi quan sát theo tháng của một tỉnh */
        get: operations["listObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách lượt dự báo */
        get: operations["listForecastRuns"];
        put?: never;
        /**
         * Tạo lượt dự báo (chạy nền). Vai trò tối thiểu `analyst`.
         * @description Luôn là job — mô hình không bao giờ chạy trong request đồng bộ (docs/09 §2 nguyên tắc 4).
         *     `backtest`: `origin_month` phải ≤ 2010-06 (giai đoạn có dữ liệu thật).
         *     `live_experimental`: kết quả luôn mang cờ `out_of_validated_period` và/hoặc `estimated_inputs`.
         */
        post: operations["createForecastRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết một lượt dự báo */
        get: operations["getForecastRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bản đồ rủi ro — dự báo 34 tỉnh cho một lượt và một tầm dự báo (BFF ghép nhiều service)
         * @description Một nguồn phụ lỗi (vd cảnh báo) → vẫn trả phần còn lại kèm `warnings[]`, không trả 500.
         */
        get: operations["getRiskMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provinces/{province_id}/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dự báo một tỉnh cho đủ các tầm dự báo của một lượt */
        get: operations["getProvinceForecasts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provinces/{province_id}/explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yếu tố ảnh hưởng dự báo (SHAP) cho một tỉnh, một tầm dự báo
         * @description Giải thích mô hình, KHÔNG phải quan hệ nhân quả.
         */
        get: operations["getProvinceExplanation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model card rút gọn của phiên bản mô hình đang dùng */
        get: operations["getModelCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-card/limitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách giới hạn đã biết (đo được) của mô hình */
        get: operations["listLimitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Các phiên bản mô hình (danh mục đóng, trả đủ — không phân trang) */
        get: operations["listModelVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trạng thái job chạy nền (polling) */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Mã tỉnh (34 tỉnh mới) — slug không dấu, khớp `new_province_code` trong ai-service/data/external/province_metadata.csv.
         * @example ho_chi_minh
         */
        ProvinceId: string;
        /**
         * @description Tháng dạng `YYYY-MM`.
         * @example 2010-03
         */
        YearMonth: string;
        /**
         * @description Tầm dự báo — số tháng tính từ tháng neo (`origin_month`).
         * @enum {integer}
         */
        Horizon: 1 | 2 | 3 | 6;
        /** @enum {string} */
        Region: "Bắc" | "Trung" | "Nam";
        /**
         * @description `real` đo thật; `estimated` ước lượng small-area (2011–2025); `imputed` điền khuyết; `simulated` giả lập.
         *     UI PHẢI phân biệt rõ, không để dữ liệu không-thật trông như thật (docs/10 luật T2).
         * @enum {string}
         */
        DataSource: "real" | "estimated" | "imputed" | "simulated";
        /** @enum {string} */
        RunMode: "backtest" | "live_experimental";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "completed" | "failed" | "interrupted" | "cancelled";
        /** @enum {string} */
        Role: "viewer" | "analyst" | "officer" | "approver" | "data_manager" | "admin";
        /**
         * @description `outbreak_underprediction_risk`: mô hình thiên thấp khi bùng dịch — cần chuyên môn xem xét.
         *     `estimated_inputs`: đầu vào có dữ liệu ước lượng. `stale_data`: dữ liệu quá hạn.
         *     `out_of_validated_period`: tháng neo sau giai đoạn đã kiểm chứng (2010).
         * @enum {string}
         */
        ForecastFlag: "outbreak_underprediction_risk" | "estimated_inputs" | "stale_data" | "out_of_validated_period";
        LoginRequest: {
            username: string;
            password: string;
        };
        TokenResponse: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /**
             * @description Số giây hiệu lực
             * @example 900
             */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            roles: components["schemas"]["Role"][];
            /** @description Đơn vị trực thuộc (CDC tỉnh / bệnh viện) — quyết định phạm vi dữ liệu được xử lý. */
            org_id: string;
        };
        Province: {
            province_id: components["schemas"]["ProvinceId"];
            /** @example Hồ Chí Minh */
            name: string;
            region: components["schemas"]["Region"];
            /** @description Dân số tham chiếu; null nếu chưa có. */
            population?: number | null;
        };
        DataVersion: {
            /** @example v0.2.0 */
            version: string;
            /** Format: date-time */
            published_at: string;
            first_month?: components["schemas"]["YearMonth"];
            last_month?: components["schemas"]["YearMonth"];
            /**
             * Format: double
             * @description Tỉ lệ dòng dữ liệu `real` trong phiên bản.
             */
            real_share: number;
        };
        Observation: {
            month: components["schemas"]["YearMonth"];
            /** Format: double */
            cases: number;
            /** Format: double */
            incidence_per_100k?: number | null;
            data_source: components["schemas"]["DataSource"];
        };
        GeoJsonFeatureCollection: {
            /** @constant */
            type: "FeatureCollection";
            features: {
                /** @constant */
                type: "Feature";
                geometry: {
                    [key: string]: unknown;
                };
                properties: {
                    province_id: components["schemas"]["ProvinceId"];
                } & {
                    [key: string]: unknown;
                };
            }[];
        };
        /** @description Provenance — bắt buộc trong mọi response chứa số liệu mô hình (docs/09 §6.5, docs/10 luật T3). */
        Meta: {
            /** Format: uuid */
            run_id: string;
            run_mode: components["schemas"]["RunMode"];
            /** @example m4-r2@1.0.0 */
            model_version: string;
            /** @example v0.2.0 */
            data_version: string;
            origin_month: components["schemas"]["YearMonth"];
            /**
             * Format: date-time
             * @description Thời điểm dữ liệu đầu vào được chốt.
             */
            as_of?: string;
            /** Format: date-time */
            generated_at: string;
            /** @example /api/v1/model-card/limitations */
            limitations_ref: string;
        };
        /** @description Độ tin cậy theo vùng (docs/07 §12.4). Bảng tĩnh gắn với phiên bản mô hình. */
        Reliability: {
            /** @enum {string} */
            region_level: "high" | "high_normal_years" | "low_in_outbreak_years" | "equal_to_seasonal_baseline";
            /**
             * @description Mã ghi chú; frontend ánh xạ sang câu chữ tiếng Việt.
             * @example bac_outbreak_years
             */
            note_code: string;
        };
        /** @description Tỉ trọng nguồn dữ liệu đầu vào của dự báo (cộng lại ≈ 1). */
        InputDataSources: {
            /** Format: double */
            real: number;
            /** Format: double */
            estimated: number;
            /** Format: double */
            imputed: number;
        };
        ForecastItem: {
            province_id: components["schemas"]["ProvinceId"];
            region: components["schemas"]["Region"];
            target_month: components["schemas"]["YearMonth"];
            horizon: components["schemas"]["Horizon"];
            /**
             * Format: double
             * @description Số ca dự báo trong tháng đích.
             */
            cases_pred: number;
            /**
             * @description Khoảng dự báo. **Hiện luôn `null`** — chưa có khoảng đã kiểm chứng độ phủ (docs/09 §10.2, Q4).
             *     UI không được tự vẽ khoảng khi null.
             */
            cases_pred_interval: null | components["schemas"]["PredictionInterval"];
            /**
             * Format: double
             * @description Xác suất số ca tháng đích vượt ngưỡng P75. LUÔN hiển thị cùng `base_rate`.
             */
            exceed_prob: number;
            /**
             * Format: double
             * @description Ngưỡng P75 cùng tháng dương lịch, cùng tỉnh, tính nhân quả.
             */
            threshold_p75: number;
            /**
             * Format: double
             * @description Tỉ lệ nền tháng vượt ngưỡng trong giai đoạn tham chiếu của phiên bản mô hình.
             */
            base_rate: number;
            input_data_sources: components["schemas"]["InputDataSources"];
            reliability: components["schemas"]["Reliability"];
            flags: components["schemas"]["ForecastFlag"][];
        };
        PredictionInterval: {
            /** Format: double */
            lower: number;
            /** Format: double */
            upper: number;
            /**
             * Format: double
             * @example 0.8
             */
            level: number;
            /** @example conformal_backtest_residuals */
            method: string;
        };
        LegendClass: {
            /** Format: double */
            min: number;
            /** Format: double */
            max: number;
            label: string;
        };
        RiskMapItem: {
            province_id: components["schemas"]["ProvinceId"];
            name: string;
            region: components["schemas"]["Region"];
            /** @description null nếu tỉnh không có dự báo trong lượt này. */
            forecast: null | components["schemas"]["ForecastItem"];
            /** @description null khi nguồn cảnh báo không khả dụng (kèm `warnings[]`); 0 ở Đợt 1. */
            open_alert_count: number | null;
        };
        Warning: {
            /** @example gateway.alerts_unavailable */
            code: string;
            message: string;
        };
        RiskMap: {
            meta: components["schemas"]["Meta"];
            horizon: components["schemas"]["Horizon"];
            /** @description Ngưỡng lớp màu do server trả — frontend không tự tính (docs/10 §11.1). */
            legend: {
                exceed_prob: components["schemas"]["LegendClass"][];
                cases_per_100k: components["schemas"]["LegendClass"][];
            };
            items: components["schemas"]["RiskMapItem"][];
            warnings: components["schemas"]["Warning"][];
        };
        ExplanationFactor: {
            /** @example cases_lag_1 */
            feature: string;
            /** @enum {string} */
            family: "recent_cases" | "seasonal_norm" | "climate" | "other";
            /**
             * Format: double
             * @description Giá trị đặc trưng đầu vào.
             */
            value: number | null;
            /**
             * Format: double
             * @description Đóng góp SHAP vào dự báo (đơn vị của đầu ra mô hình).
             */
            contribution: number;
        };
        Explanation: {
            meta: components["schemas"]["Meta"];
            province_id: components["schemas"]["ProvinceId"];
            horizon: components["schemas"]["Horizon"];
            /**
             * Format: double
             * @description Giá trị nền (kỳ vọng) của mô hình.
             */
            base_value: number;
            /** @description Top-k yếu tố theo |contribution| giảm dần. */
            factors: components["schemas"]["ExplanationFactor"][];
        };
        ForecastRun: {
            /** Format: uuid */
            run_id: string;
            run_mode: components["schemas"]["RunMode"];
            status: components["schemas"]["RunStatus"];
            origin_month: components["schemas"]["YearMonth"];
            model_version: string;
            data_version: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            error_code?: string | null;
        };
        CreateForecastRunRequest: {
            mode: components["schemas"]["RunMode"];
            origin_month: components["schemas"]["YearMonth"];
            /** @description Mặc định là phiên bản `approved` hiện hành. */
            model_version?: string;
            /** @description Mặc định là bản mới nhất. */
            data_version?: string;
        };
        Job: {
            /** Format: uuid */
            job_id: string;
            /**
             * @example forecast_run
             * @enum {string}
             */
            kind: "forecast_run";
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Format: double */
            progress?: number | null;
            /** @description URL tài nguyên kết quả khi thành công (vd `/api/v1/forecast-runs/{id}`). */
            result_ref?: string | null;
            error_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        ModelVersion: {
            /** @example m4-r2@1.0.0 */
            model_version: string;
            /** @enum {string} */
            status: "candidate" | "approved" | "retired";
            description: string;
            source_experiments?: string[];
        };
        ModelCard: {
            model_version: string;
            intended_use: string;
            not_for: string[];
            performance: {
                /** @description Đánh giá nhiều mùa (exp_016) so với baseline B3 — không chỉ mùa 2010 (khó nhất). */
                multi_season: {
                    seasons: number;
                    /** Format: double */
                    mase_pooled_mean: number;
                    /** Format: double */
                    mase_pooled_sd: number;
                    beats_baseline_seasons: number;
                    improvement_vs_baseline: {
                        /** Format: double */
                        mean: number;
                        /** Format: double */
                        ci95_lower: number;
                        /** Format: double */
                        ci95_upper: number;
                    };
                };
                alerting: {
                    /** Format: double */
                    roc_auc_mean: number;
                    /** Format: double */
                    roc_auc_sd: number;
                    base_rate_range: number[];
                };
            };
            reliability_by_region: {
                "B\u1EAFc": components["schemas"]["Reliability"];
                Trung: components["schemas"]["Reliability"];
                Nam: components["schemas"]["Reliability"];
            };
            /** Format: date-time */
            updated_at: string;
        };
        Limitation: {
            /** @example L1 */
            id: string;
            title: string;
            summary: string;
            /** @enum {string} */
            severity: "info" | "moderate" | "high";
            /**
             * @description Tham chiếu experiment/mục model card chứa số đo.
             * @example exp_016 §Bắc
             */
            evidence: string;
        };
        /** @description RFC 9457 problem details (docs/09 §6.3). */
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            /**
             * @description Mã lỗi ổn định dạng `<service>.<snake_case>` — danh mục ở contracts/errors.md.
             * @example common.validation_error
             */
            code: string;
            detail?: string;
            instance?: string;
            request_id: string;
            errors?: {
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Đầu vào không hợp lệ (`code` = `common.validation_error`). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Chưa xác thực hoặc token hết hạn. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Không đủ quyền. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Không tìm thấy. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Xung đột trạng thái. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Vượt giới hạn tần suất. */
        TooManyRequests: {
            headers: {
                /** @description Số giây nên chờ. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Mã tỉnh mới (34 tỉnh, NQ 202/2025/QH15) dạng slug không dấu, vd `ho_chi_minh`. */
        ProvinceId: components["schemas"]["ProvinceId"];
        RunId: string;
        Limit: number;
        /** @description Con trỏ mờ (opaque) lấy từ `next_cursor`. */
        Cursor: string;
        /** @description UUID do client sinh cho mỗi lần người dùng thao tác; gửi lại cùng key trả lại đúng response cũ (24 giờ). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Thành công. Refresh token được đặt trong cookie `HttpOnly; Secure; SameSite=Strict; Path=/api/v1/auth`. */
            200: {
                headers: {
                    /** @description Cookie refresh token (HttpOnly). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access token mới; cookie refresh được xoay vòng. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã đăng xuất */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProvinces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Province"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProvince: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mã tỉnh mới (34 tỉnh, NQ 202/2025/QH15) dạng slug không dấu, vd `ho_chi_minh`. */
                province_id: components["parameters"]["ProvinceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Province"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProvinceGeometry: {
        parameters: {
            query?: {
                /** @description Phiên bản ranh giới; mặc định là bản mới nhất. Response có `Cache-Control` dài khi chỉ định version. */
                version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON FeatureCollection; mỗi feature có `properties.province_id`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["GeoJsonFeatureCollection"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDataVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DataVersion"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listObservations: {
        parameters: {
            query: {
                province_id: components["schemas"]["ProvinceId"];
                from?: components["schemas"]["YearMonth"];
                to?: components["schemas"]["YearMonth"];
                /** @description Mặc định là bản mới nhất. */
                data_version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data_version: string;
                        items: components["schemas"]["Observation"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listForecastRuns: {
        parameters: {
            query?: {
                mode?: components["schemas"]["RunMode"];
                status?: components["schemas"]["RunStatus"];
                limit?: components["parameters"]["Limit"];
                /** @description Con trỏ mờ (opaque) lấy từ `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK (mới nhất trước) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ForecastRun"][];
                        next_cursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createForecastRun: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID do client sinh cho mỗi lần người dùng thao tác; gửi lại cùng key trả lại đúng response cũ (24 giờ). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateForecastRunRequest"];
            };
        };
        responses: {
            /** @description Đã nhận, chạy nền. */
            202: {
                headers: {
                    /** @description URL của job (`/api/v1/jobs/{job_id}`). */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getForecastRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRiskMap: {
        parameters: {
            query: {
                /** @description Mặc định là lượt `completed` mới nhất. */
                run_id?: string;
                horizon: components["schemas"]["Horizon"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskMap"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProvinceForecasts: {
        parameters: {
            query?: {
                run_id?: string;
            };
            header?: never;
            path: {
                /** @description Mã tỉnh mới (34 tỉnh, NQ 202/2025/QH15) dạng slug không dấu, vd `ho_chi_minh`. */
                province_id: components["parameters"]["ProvinceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        meta: components["schemas"]["Meta"];
                        items: components["schemas"]["ForecastItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProvinceExplanation: {
        parameters: {
            query: {
                run_id?: string;
                horizon: components["schemas"]["Horizon"];
            };
            header?: never;
            path: {
                /** @description Mã tỉnh mới (34 tỉnh, NQ 202/2025/QH15) dạng slug không dấu, vd `ho_chi_minh`. */
                province_id: components["parameters"]["ProvinceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getModelCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCard"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLimitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        model_version: string;
                        items: components["schemas"]["Limitation"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listModelVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ModelVersion"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
