// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AlertStatus.
const (
	AlertStatusClosed AlertStatus = "closed"
	AlertStatusOpen   AlertStatus = "open"
)

// Valid indicates whether the value is a known member of the AlertStatus enum.
func (e AlertStatus) Valid() bool {
	switch e {
	case AlertStatusClosed:
		return true
	case AlertStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for ListAlertsParamsStatus.
const (
	ListAlertsParamsStatusAll    ListAlertsParamsStatus = "all"
	ListAlertsParamsStatusClosed ListAlertsParamsStatus = "closed"
	ListAlertsParamsStatusOpen   ListAlertsParamsStatus = "open"
)

// Valid indicates whether the value is a known member of the ListAlertsParamsStatus enum.
func (e ListAlertsParamsStatus) Valid() bool {
	switch e {
	case ListAlertsParamsStatusAll:
		return true
	case ListAlertsParamsStatusClosed:
		return true
	case ListAlertsParamsStatusOpen:
		return true
	default:
		return false
	}
}

// Alert defines model for Alert.
type Alert struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	ProvinceId string             `json:"province_id"`
	RunId      openapi_types.UUID `json:"run_id"`
	Status     AlertStatus        `json:"status"`
}

// AlertStatus defines model for Alert.Status.
type AlertStatus string

// Case defines model for Case.
type Case struct {
	AlertId   openapi_types.UUID `json:"alert_id"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
}

// ListAlertsParams defines parameters for ListAlerts.
type ListAlertsParams struct {
	// Status Lọc theo trạng thái
	Status *ListAlertsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// RunId Lọc theo lượt dự báo
	RunId *openapi_types.UUID `form:"run_id,omitempty" json:"run_id,omitempty"`
}

// ListAlertsParamsStatus defines parameters for ListAlerts.
type ListAlertsParamsStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAlerts Danh sách cảnh báo
	// (GET /internal/v1/workflow/alerts)
	ListAlerts(c *gin.Context, params ListAlertsParams)
	// ConfirmAlert Xác nhận cảnh báo để mở hồ sơ
	// (POST /internal/v1/workflow/alerts/{alert_id}/confirm)
	ConfirmAlert(c *gin.Context, alertId openapi_types.UUID)
	// ListCases Danh sách hồ sơ
	// (GET /internal/v1/workflow/cases)
	ListCases(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAlerts operation middleware
func (siw *ServerInterfaceWrapper) ListAlerts(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAlertsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "run_id", c.Request.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter run_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAlerts(c, params)
}

// ConfirmAlert operation middleware
func (siw *ServerInterfaceWrapper) ConfirmAlert(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "alert_id" -------------
	var alertId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "alert_id", c.Param("alert_id"), &alertId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter alert_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmAlert(c, alertId)
}

// ListCases operation middleware
func (siw *ServerInterfaceWrapper) ListCases(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCases(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/internal/v1/workflow/alerts", wrapper.ListAlerts)
	router.POST(options.BaseURL+"/internal/v1/workflow/alerts/:alert_id/confirm", wrapper.ConfirmAlert)
	router.GET(options.BaseURL+"/internal/v1/workflow/cases", wrapper.ListCases)
}

type ListAlertsRequestObject struct {
	Params ListAlertsParams
}

type ListAlertsResponseObject interface {
	VisitListAlertsResponse(w http.ResponseWriter) error
}

type ListAlerts200JSONResponse []Alert

func (response ListAlerts200JSONResponse) VisitListAlertsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmAlertRequestObject struct {
	AlertId openapi_types.UUID `json:"alert_id"`
}

type ConfirmAlertResponseObject interface {
	VisitConfirmAlertResponse(w http.ResponseWriter) error
}

type ConfirmAlert204Response struct {
}

func (response ConfirmAlert204Response) VisitConfirmAlertResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ListCasesRequestObject struct {
}

type ListCasesResponseObject interface {
	VisitListCasesResponse(w http.ResponseWriter) error
}

type ListCases200JSONResponse []Case

func (response ListCases200JSONResponse) VisitListCasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAlerts Danh sách cảnh báo
	// (GET /internal/v1/workflow/alerts)
	ListAlerts(ctx context.Context, request ListAlertsRequestObject) (ListAlertsResponseObject, error)
	// ConfirmAlert Xác nhận cảnh báo để mở hồ sơ
	// (POST /internal/v1/workflow/alerts/{alert_id}/confirm)
	ConfirmAlert(ctx context.Context, request ConfirmAlertRequestObject) (ConfirmAlertResponseObject, error)
	// ListCases Danh sách hồ sơ
	// (GET /internal/v1/workflow/cases)
	ListCases(ctx context.Context, request ListCasesRequestObject) (ListCasesResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListAlerts operation middleware
func (sh *strictHandler) ListAlerts(ctx *gin.Context, params ListAlertsParams) {
	var request ListAlertsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAlerts(ctx, request.(ListAlertsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAlerts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListAlertsResponseObject); ok {
		if err := validResponse.VisitListAlertsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConfirmAlert operation middleware
func (sh *strictHandler) ConfirmAlert(ctx *gin.Context, alertId openapi_types.UUID) {
	var request ConfirmAlertRequestObject

	request.AlertId = alertId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmAlert(ctx, request.(ConfirmAlertRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmAlert")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ConfirmAlertResponseObject); ok {
		if err := validResponse.VisitConfirmAlertResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCases operation middleware
func (sh *strictHandler) ListCases(ctx *gin.Context) {
	var request ListCasesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListCases(ctx, request.(ListCasesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCases")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListCasesResponseObject); ok {
		if err := validResponse.VisitListCasesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
